### ISSUE TITLE
Windows 10 Bitlock Support

### ISSUE THREAD

**Issue by marmina** [Aorimn/dislocker#100]
# There is A new Bit lock Version From windows 10 and it's not compatible with other windows version and must be encrypted to compatible version i am didn't test it but i think dislocker didn't support it yet 
https://technet.microsoft.com/en-us/itpro/windows/whats-new/whats-new-windows-10-version-1507-and-1511#bitlocker

**Comment by Aorimn** [comment]
Hi,
dislocker already supports it.

**Comment by marmina** [comment]
Thanks For Answer
