### ISSUE TITLE
The signature of the volume (NTFS    ) doesn't match the BitLocker's

### ISSUE THREAD

**Issue by scojopa** [Aorimn/dislocker#104]
I cannot seem to get this working. I have the Bitlocker PIN and Recovery Password. This drive came from a Lenovo Thinkpad (TPM) What am I doing wrong? 

Device       Start       End   Sectors   Size Type
/dev/sdb1     2048    923647    921600   450M Windows recovery environment
/dev/sdb2   923648   1128447    204800   100M EFI System
/dev/sdb3  1128448   1161215     32768    16M Microsoft reserved
/dev/sdb4  1161216 488396799 487235584 232.3G Microsoft basic data

sudo dislocker -vvv -V /dev/sdb1 -u"BITLOCKERPIN" -- /media/bitlocker
Fri Mar  3 17:36:42 2017 [INFO] dislocker by Romain Coltel, v0.7.1 (compiled for Linux/x86_64)
Fri Mar  3 17:36:42 2017 [INFO] Compiled version: :
Fri Mar  3 17:36:42 2017 [ERROR] The signature of the volume (NTFS    ) doesn't match the BitLocker's ones (-FVE-FS- or MSWIN4.1). Abort.
Fri Mar  3 17:36:42 2017 [CRITICAL] Cannot parse volume header. Abort.

**Comment by Aorimn** [comment]
Hi,

First of all, the `-u` option is for the user password only, not the PIN, which is computed using the TPM and thus not supported by dislocker. You'll need the recovery password to decrypt your partition.

Then, the partition you're trying to decrypt is already decrypted, so there's no need of dislocker. However, have a look at /dev/sdb2, it might contain what you're looking for.

**Comment by scojopa** [comment]
Tried using -p on all partitions. 
Disk /dev/sdb: 232.9 GiB, 250059350016 bytes, 488397168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 6A248B7A-E2AC-4060-9117-2D6842D2C477

Device       Start       End   Sectors   Size Type
/dev/sdb1     2048    923647    921600   450M Windows recovery environment
/dev/sdb2   923648   1128447    204800   100M EFI System
/dev/sdb3  1128448   1161215     32768    16M Microsoft reserved
/dev/sdb4  1161216 488396799 487235584 232.3G Microsoft basic data

sp@777 ~ $ sudo dislocker -vvv -r -V /dev/sdb4 -pxxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx -- /media/bitlocker
Mon Mar  6 08:39:12 2017 [INFO] dislocker by Romain Coltel, v0.7.1 (compiled for Linux/x86_64)
Mon Mar  6 08:39:12 2017 [INFO] Compiled version: :
Mon Mar  6 08:39:12 2017 [ERROR] Failed to read in #3: Input/output error
Mon Mar  6 08:39:12 2017 [CRITICAL] Error during reading the volume: not enough byte read.
sp@777 ~ $ sudo dislocker -vvv -r -V /dev/sdb3 -pxxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx -- /media/bitlocker
Mon Mar  6 08:39:53 2017 [INFO] dislocker by Romain Coltel, v0.7.1 (compiled for Linux/x86_64)
Mon Mar  6 08:39:53 2017 [INFO] Compiled version: :
Mon Mar  6 08:39:53 2017 [ERROR] The sector size found is null.
Mon Mar  6 08:39:53 2017 [CRITICAL] Cannot parse volume header. Abort.
sp@777 ~ $ sudo dislocker -vvv -r -V /dev/sdb2 -pxxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx -- /media/bitlocker
Mon Mar  6 08:40:03 2017 [INFO] dislocker by Romain Coltel, v0.7.1 (compiled for Linux/x86_64)
Mon Mar  6 08:40:03 2017 [INFO] Compiled version: :
Mon Mar  6 08:40:03 2017 [ERROR] The signature of the volume (MSDOS5.0) doesn't match the BitLocker's ones (-FVE-FS- or MSWIN4.1). Abort.
Mon Mar  6 08:40:03 2017 [CRITICAL] Cannot parse volume header. Abort.

**Comment by Aorimn** [comment]
Yeah weird. According to the partition's sizes, I would go for /dev/sdb4 being the encrypted partition (not sdb2 like I said before), but there isn't a standard signature. You might try to change MSWIN4.1 in [include/dislocker/common.h](https://github.com/Aorimn/dislocker/blob/6a92e9bd36440fc569bd216db596a9927b1a6af6/include/dislocker/common.h#L50) into MSDOS5.0, then re-run dislocker (using the `-r` option to be sure you won't mess things up in your partition), that might work. Let me know if it does, I'll include this fix. Do you know how you did format the drive's filesystem?

**Comment by ericpaul88** [comment]
root@laptop:~# dislocker -vvv -V /dev/sdb1 -u -- /mnt/stuff/
Sat Jun 17 10:52:14 2017 [INFO] dislocker by Romain Coltel, v0.7.1 (compiled for Linux/x86_64)
Sat Jun 17 10:52:17 2017 [INFO] Volume has EOW_INFORMATION_OFFSET_GUID.
Sat Jun 17 10:52:17 2017 [ERROR] Failed to read in #3: Bad address
Sat Jun 17 10:52:17 2017 [ERROR] get_eow_information::Error, not all bytes read: -1, -8 expected (2).
Sat Jun 17 10:52:17 2017 [ERROR] Getting EOW information at offset c07f0000 failed
Sat Jun 17 10:52:17 2017 [ERROR] EOW volume GUID not supported.
Sat Jun 17 10:52:17 2017 [CRITICAL] Cannot parse volume header. Abort.

Please help
i left my bitlocker in decryption and without the process being completed installed linux now i am not able to see my drive
