### ISSUE TITLE
Decrypting VHDX file

### ISSUE THREAD

**Issue by mooop12** [Aorimn/dislocker#106]
I have a Bitlocker encrypted partition that's in a VHDX file, can it be decrypted with dislocker?

**Comment by Aorimn** [comment]
I don't really know about this format, so I won't be able to fully answer your question. However, one sure thing is a variable-size VHDX won't be decryptable. A fixed-size VHDX might be decryptable, probably using an offset to get dislocker to go to the beginning of the real partition if so, but it'll be impossible for a variable-size one.

**Comment by Manouchehri** [comment]
Just convert or mount the image first and Dislocker should work.

**Comment by mooop12** [comment]
Since that file would now be hosted on my NAS, I decided to switch to TrueCrypt, which is supported on both Linux and Windows. I used BitLocker with VHDX initially because I could set the file to grow as I put in more data. I can't do that with TrueCrypt, but I'll live.

**Comment by paulstelian97** [comment]
Additional software to mount the VHDX is needed.
