### ISSUE TITLE
Stupid question? after installation, see "dislocker(1)" for details

### ISSUE THREAD

**Issue by kylinsuqilin** [Aorimn/dislocker#109]
I cannot find dislocker(1)...where is it??? :(

**Comment by rossica** [comment]
I believe it means to run the command:
`man 1 dislocker`
From a terminal window to see the help/manual

-----Original Message-----

**Comment by kylinsuqilin** [comment]
returned "No entry for dislocker in section 1 of the manual"

**Comment by eddiek2000** [comment]
try 'man dislocker'

**Comment by Aorimn** [comment]
Hi @kylinsuqilin,
How did you install dislocker, on which version of which OS? dislocker's man page can be found [here](https://github.com/Aorimn/dislocker/tree/master/man) (you'll probably want `dislocker-fuse`).

@rossica, @eddiek2000 : thanks for your help! That's really nice to see the community respond!
