### ISSUE TITLE
Can't mount dislocker-file

### ISSUE THREAD

**Issue by pentago** [Aorimn/dislocker#112]
Even tough I have loop module loaded, mounting dislocker-file throws loop-related error.

```
# mount -o ro,loop dis/dislocker-file bit
mount: dis/dislocker-file: failed to setup loop device: Permission denied
```
Using dislocker on latest Arch with 4.11.3 kernel.
Any ideas on what can be the cause?
Thanks!

**Comment by Aorimn** [comment]
Did you try manually linking the file to a loop device, and only then mount the loop device?
