### ISSUE TITLE
arch

### ISSUE THREAD

**Issue by MortezaMoFa** [Aorimn/dislocker#116]
I'm trying install on:
`Linux manjaro-pc 4.9.13-1-MANJARO #1 SMP PREEMPT Sun Feb 26 13:27:28 UTC 2017 x86_64 GNU/Linux
`
but ... .
can I install on manjaro gnu/linux?

**Comment by Aorimn** [comment]
Hi @MortezaMoFa!
I've never tested it on such platform, but as it's a linux distribution, I'd expect it to work pretty much the same. Do you have any log that suggest it wouldn't be possible?
