### ISSUE TITLE
How to clean dislocker-file other than reboot for unother round of dislocking?

### ISSUE THREAD

**Issue by cnzhx** [Aorimn/dislocker#120]
Sorry to bother with this silly question. I just could not find an answer on the web.

Maybe I used it incorrect. Here is what I do: 

- Use dislocker to dislock a partition on USB drive
- Mount with `mount -o loop,rw dislocker-file /mnt/folder`
- Umount /mnt/folder (or something like it) and unplug the USB drive

But before a reboot of the OS, I couldn't plug in the USB drive and dislock it to the same directory because the `dislocker-file` is still there from last time I used it.

What's the right approach to use dislocker or to use dislocker again before reboot?

And, after the question, I want to seriously express my thanks for this great app.

**Comment by mabentwickeltsich** [comment]
Hey @cnzhx ,

You need to read the man page of dislocker (`man dislocker`); you are missing something.

You need to unmount the NTFS partition and the dislocker-file

    umount /mnt/folder
    umount /path/to/dislocker-file

Then you can unplug the USB drive without problems.

Cheers
Luis

**Comment by cnzhx** [comment]
Hi Luis,
Thank you very much! 
I am shamed that I am still not getting used to do `man` check. I have read the online document but I must have missed the part of `% umount /mnt/clear && umount /mnt/ntfs/dislocker-file`.
Cheers,
Haoxian
