### ISSUE TITLE
how to safely unmount and remove dislocker-file

### ISSUE THREAD

**Issue by jar349** [Aorimn/dislocker#121]
dislocker 0.7.1 is working fine for me in linux mint 18.2 (ubuntu 16.04).  So that you understand my question, here's what I've done:
```
sudo dislocker -v -V /dev/sda5 -pmy-key-was-here -- /mnt/storage
sudo mount -o loop,rw /mnt/storage/dislocker-file /storage
```
Once I'm done with the encrypted volume, I can `sudo umount /storage` but `/mnt/storage/dislocker-file` remains.  How do I correctly/safely get rid of the `/mnt/storage/dislocker-file` file?

**Comment by mabentwickeltsich** [comment]
This duplicates issue #120 which is already solved.

Hi @jar349 

Just unmount the dislocker file.

Cheers
Luis

**Comment by Aorimn** [comment]
Indeed, thanks @mabentwickeltsich.
