### ISSUE TITLE
Mount writeable

### ISSUE THREAD

**Issue by crilleengvall** [Aorimn/dislocker#123]
Hi!
Thanks for this awesome software.
This is more of a question than a bug report, but i didn't know where to post it.

I'm trying to mount a disk as writeable on MacOS High Sierra, but i can't figure out how to achieve that. But i think i'm supposed to be able to get that to work since dislockers description states 
`"FUSE driver to read/write Windows' BitLocker-ed volumes under Linux / Mac OSX"` ?

I have a bitlocker encrypted external hard drive which i use dislocker to decrypt with this command:
`sudo dislocker -vvv -V /dev/disk2s1 -u -- /mnt/externalhdd/`

then i run this command to create a block device:
`sudo hdiutil attach -imagekey diskimage-class=CRawDiskImage -nomount /mnt/externalhdd/dislocker-file`

And then i mount it using this command:
`sudo mount -t ntfs /dev/disk3 /Volumes/ExternalHDD/`
This works, but is only readable.

Also tried to add -w when mounting,
`sudo mount -t ntfs -w /dev/disk3 /Volumes/ExternalHDD/`
Still gets only read-permissions

Running this:
`sudo mount -t ntfs -o w,auto /dev/disk3 /Volumes/ExternalHDD/`
creates this error
`mount_ntfs: -o w: option not supported`

Am i doing something wrong or am i trying to achieve something that isn't possible?

**Comment by rossica** [comment]
The NTFS driver included with macOS doesn't support writing to NTFS file systems. It only supports read-only.
There are third party NTFS drivers for macOS which add write support, but not all of them are free or open source.

Use your favorite search engine and search for "macOS NTFS write support" and you'll find something.

-----Original Message-----

**Comment by crilleengvall** [comment]
Thank you @rossica!
I'll check that out!

**Comment by Menci** [comment]
@rossica @crilleengvall No, macOS's NTFS driver ***can*** mount NTFS as read & write. You just entered the ***wrong*** command.

Replace

```
sudo mount -t ntfs -o w,auto /dev/disk3 /Volumes/ExternalHDD/
```

with

```
sudo mount -t ntfs -o rw,auto,nobrowse /dev/disk3 /Volumes/ExternalHDD/
```

Notice the option `rw` and `nobrowse`.

So now let's open & test it

```
open /Volumes/ExternalHDD/
```

I think it's more stable than third-party tools such as `ntfs-3g`.

**Comment by crilleengvall** [comment]
Thanks @Menci !
