### ISSUE TITLE
Is it possible?

### ISSUE THREAD

**Issue by magnum93** [Aorimn/dislocker#128]
Hi there, 

I am involved in a project which involves laptop data which is bitlocked.  As an admin I have the recovery keys which have been stored in active directory.  What I would like to do, as we have many of them is to pull the drive from a laptop, connect it to a linux system, unlock with dislocker, pull the data from the drive.

Will this utility work for just that purpose? - as it would speed up the migration of the data which all the users have gathered on their local c drives.

I am just asking kindly if I am looking in the right place for this job. Can you tell me will this utility work for what I just described thankyou.

**Comment by magnum93** [comment]
I would like to ad what would really speed thinks up, if I was using a persistent usb drive with linux and dislocker installed on, I would like to boot off the key, and then copy the users unlocked data straight back into the windows folder which linux can see.  At the moment I am having to take the drive out of the laptop and connect it to another windows system, enter the unlock key then copy the data to an external drive, it would be much faster if I could gain access to the windows folder on the new laptop and copy the data straight back.

**Comment by kenkit** [comment]
It's not that hard, even scripts can get the job done.

**Comment by Aorimn** [comment]
@magnum93 : yes, dislocker can be installed on a linux-running usb key. You might want to try ubuntu or kali, which have dislocker packaged IIRC.
