### ISSUE TITLE
Bitlocker encrypted partition

### ISSUE THREAD

**Issue by hulu5555** [Aorimn/dislocker#129]
i encrypted my partition (490GB,NTFS) in window 10, but i forget to remove decryption of this partition,Now i'm using ubuntu,, i can't see/mount this partition, which is sda2, Anyhow i could access,yes i know password,, i tried with **sudo dislocker -r -V /dev/sda2 -uMY_PASSWD -- /media/Drive1** == error is **[CRITICAL] Cannot parse volume header. Abort**------------{HDD SIZE=1TB}

**Comment by Aorimn** [comment]
That error means the `/dev/sda2` partition isn't recognized as a BitLocker encrypted partition.
Can you post the output of `fdisk -l`, if your windows partition is indeed around 490GB?

**Comment by Kyasai** [comment]
> That error means the `/dev/sda2` partition isn't recognized as a BitLocker encrypted partition.
> Can you post the output of `fdisk -l`, if your windows partition is indeed around 490GB?

I have the same problem on ubuntu 19.04
This is my bitlocker locked device:

```
Disk /dev/sdc: 931.5 GiB, 1000204886016 bytes, 1953525168 sectors
Disk model: HV620           
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x591f5c7e

```
And I have tried the following commands:
```
$ sudo ntfsfix /dev/sdc
Mounting volume... NTFS signature is missing.
FAILED
Attempting to correct errors... NTFS signature is missing.
FAILED
Failed to startup volume: Invalid argument
NTFS signature is missing.
Trying the alternate boot sector
Unrecoverable error
Volume is corrupt. You should run chkdsk.

```
And:

`sudo dislocker /dev/sdc -u<password> -- /media/bitlocker
Fri Aug 16 22:44:12 2019 [CRITICAL] Cannot parse volume header. Abort.
`

**Comment by Aorimn** [comment]
It doesn't seem like this is the right partition, or maybe it's not bitlocker-software-encrypted and it's hardware-encrypted which is outside of the scope of this project. I'm closing this.
