### ISSUE TITLE
lost page write due to I/O error on loop1

### ISSUE THREAD

**Issue by superbonaci** [Aorimn/dislocker#13]
Copying a big file to the encrypted usb pendrive. Tried a lot of times and always fails after performing md5 checksum. It only seems to work for small files. Apparently the error triggers always when the file exceeds a specified size, and sometimes on lower sizes.

[  115.628640] usb 2-1.2: new high-speed USB device number 5 using ehci-pci
[  115.815027] usb 2-1.2: New USB device found, idVendor=058f, idProduct=6387
[  115.815033] usb 2-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  115.815038] usb 2-1.2: Product: Mass Storage Device
[  115.815041] usb 2-1.2: Manufacturer: Generic
[  115.815044] usb 2-1.2: SerialNumber: 2NSFNRH4
[  115.815562] usb-storage 2-1.2:1.0: USB Mass Storage device detected
[  115.816135] usb-storage 2-1.2:1.0: Quirks match for vid 058f pid 6387: 400
[  115.816179] scsi7 : usb-storage 2-1.2:1.0
[  116.817075] scsi 7:0:0:0: Direct-Access     JetFlash TS2GJF150        8.07 PQ: 0 ANSI: 2
[  116.817744] sd 7:0:0:0: Attached scsi generic sg4 type 0
[  116.818727] sd 7:0:0:0: [sdd] 4095998 512-byte logical blocks: (2.09 GB/1.95 GiB)
[  116.819333] sd 7:0:0:0: [sdd] Write Protect is off
[  116.819340] sd 7:0:0:0: [sdd] Mode Sense: 03 00 00 00
[  116.819998] sd 7:0:0:0: [sdd] No Caching mode page found
[  116.820004] sd 7:0:0:0: [sdd] Assuming drive cache: write through
[  116.823725] sd 7:0:0:0: [sdd] No Caching mode page found
[  116.823731] sd 7:0:0:0: [sdd] Assuming drive cache: write through
[  116.825514]  sdd: sdd1
[  116.827967] sd 7:0:0:0: [sdd] No Caching mode page found
[  116.827972] sd 7:0:0:0: [sdd] Assuming drive cache: write through
[  116.827977] sd 7:0:0:0: [sdd] Attached SCSI removable disk
[  151.093172] fuse init (API version 7.22)
[  825.672248] perf samples too long (2511 > 2500), lowering kernel.perf_event_max_sample_rate to 50000
[ 1316.695257] loop: Write error at byte offset 1409003520, length 4096.
[ 1316.695263] Buffer I/O error on device loop1, logical block 343995
[ 1316.695265] lost page write due to I/O error on loop1
[ 1437.050065] loop: Write error at byte offset 1408933888, length 4096.
[ 1437.050073] Buffer I/O error on device loop1, logical block 343978
[ 1437.050075] lost page write due to I/O error on loop1
[ 1704.457363] loop: Write error at byte offset 34676736, length 4096.
[ 1704.457369] Buffer I/O error on device loop1, logical block 8466
[ 1704.457370] lost page write due to I/O error on loop1
[ 1998.417629] usb 2-1.2: USB disconnect, device number 5

**Comment by superbonaci** [comment]
The mega file was removed for no reason. Could you re-upload it if you still have it?

**Comment by Aorimn** [comment]
Sorry, I've not kept the file
