### ISSUE TITLE
Problem when having a equals-sign (=) in the password?

### ISSUE THREAD

**Issue by joacim-boive** [Aorimn/dislocker#130]
dislocker v0.7.1
macOS 10.13.2

dislocker -V /dev/disk3 -v -user-password=something=something -- ./tmp

Getting: event not found

Suspecting that it's because my password contains an: =

How can I get around that?

**Comment by joacim-boive** [comment]
Nope that wasn't it.

I used a virtual instance of Windows to change the password and remote the "=".

**Comment by thinrope** [comment]
So, please close this as either invalid or resolved, if you found a way.

**Comment by joacim-boive** [comment]
The "solution" is to not have a equasign in your password. ;)

**Comment by Aorimn** [comment]
Weird, I'm using the regular `getopt` from the libc, I expect it to support having multiple equal signs in there.
Just to be sure: in your example above, you've used the option `-user-password`, but this should be `--user-password` (two leading dashes for long options). It's just in your example, right? You're actually using `--` in your real case?
