### ISSUE TITLE
Problem setting bitlocker with fstab

### ISSUE THREAD

**Issue by cazdli** [Aorimn/dislocker#131]
I'm trying to set up dislocker to unlock my encrypted drives at boot with fstab, but it doesn't seem to work for me.

What I have on my fstab.

/dev/sdd1 /mnt/Backup fuse.dislocker recovery-password=blah,nofail 0 0

When I have that on my fstab and I boot, the Backup folder in /mnt/ disappears. If I take it off fstab it appears again. Any help would be appreciated. Thanks.

Distro: Archlinux
dislocker version: 0.7.1-2

**Comment by Aorimn** [comment]
Two things would help us help you debug this issue:
- Can you mount the volume outside of fstab, directly with the dislocker command?
- Are the options you're using on this command the same as the one you're using in your fstab?

**Comment by cazdli** [comment]
I can mount the volume outside of fstab with the dislocker command, and I believe they are the same as the command on fstab, although I assumed I wouldn't need to mount it on /mnt/dis
For your reference, these are the commands I use to unlock it with dislocker.

`sudo dislocker -v -V /dev/sdd1 -pInsertNumbersHere -- /mnt/Backup`
`sudo mount -o loop,rw /mnt/Backup/dislocker-file /mnt/dis`

**Comment by Aorimn** [comment]
You will indeed need to mount `/mnt/Backup/dislocker-file` on `/mnt/dis` with the fstab too.
But what I don't understand is the disappearance of the /mnt/Backup folder. This should (and is as far as I test it) create the `dislocker-file` file in the folder, not hide it somehow.

**Comment by feugy** [comment]
Hey @cazdli.
Here is my `/etc/fstab` (Linux Mint 18.3 cinnamon):

```
# Windows' NTFS Disk C:/
/dev/sda3	/mnt/drive-c	fuse.dislocker	recovery-password=000000-000000-000000-000000-000000-000000-000000-000000	0	0
/mnt/drive-c/dislocker-file	/mnt/windows	auto	nofail,x-gvfs-show,x-gvfs-name=C:	0	0
```

Nano file explorer is showing both mount points.

![image](https://user-images.githubusercontent.com/186268/38192687-5b90e360-366e-11e8-8f0c-3917c46ccd5a.png)

I didn't managed to hide the loop one, so I renamed it to `C:`. Obviously it's not readable.

**Comment by Aorimn** [comment]
Thanks for this nice example @feugy

**Comment by jvdi** [comment]
I have same confile like @feugy but it's not work in fstab (in restart system) - just work out of fstab and work with
`sudo mount -a`
os: Fedora

**Comment by tpd1864blake** [comment]
> I didn't managed to hide the loop one, so I renamed it to `C:`. Obviously it's not readable.

sorry for bumping this, but I did manage to hide the loop partition that shows up. I set the name with `x-gvfs-name="C: (Windows)"` which seems to confuse it and cause it to not show up in the file list. Maybe it's the quotation marks, or maybe the spaces, idk
