### ISSUE TITLE
fatal error: fuse.h: No such file or directory  # include <fuse.h>

### ISSUE THREAD

**Issue by baba2k18** [Aorimn/dislocker#134]
Hi,

Im very new to Linux, so bare with me :). The issue is that a BSOD is preventing me from starting up my laptop, and thats why Im using Knoppix to access my files on my bitlocker partitioned drive and copy them over. I have my bitlocker recovery key and Im using dislocker to do this but Im stopped at the following error during compiling:

root@Microknoppix:/home/knoppix/Downloads/dislocker-0.6.1/dislocker# make
[ 78%] Built target dislocker
[ 81%] Building C object src/CMakeFiles/dislocker-fuse.dir/dislocker-fuse.c.o
/home/knoppix/Downloads/dislocker-0.6.1/dislocker/src/dislocker-fuse.c:39:19: fatal error: fuse.h: No such file or directory
 # include <fuse.h>
                   ^
compilation terminated.
src/CMakeFiles/dislocker-fuse.dir/build.make:62: recipe for target 'src/CMakeFiles/dislocker-fuse.dir/dislocker-fuse.c.o' failed
make[2]: *** [src/CMakeFiles/dislocker-fuse.dir/dislocker-fuse.c.o] Error 1
CMakeFiles/Makefile2:161: recipe for target 'src/CMakeFiles/dislocker-fuse.dir/all' failed
make[1]: *** [src/CMakeFiles/dislocker-fuse.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Any idea what Im doing wrong?

Tnx!

**Comment by Rondom** [comment]
Any reason why you want to compile dislocker yourself? It has been a very looong time I last used Knoppix, but I faintly remember that you could install Debian packages. So try

    sudo apt-get update && sudo apt-get install dislocker

For the problem at hand you need the libfuse-header:

    sudo apt-get update && sudo apt-get install libfuse-dev

**Comment by Aorimn** [comment]
Thanks for the reply @Rondom
