### ISSUE TITLE
I can't see files mounted with dislocker

### ISSUE THREAD

**Issue by diarch77** [Aorimn/dislocker#135]
Hello,
Pardon me, as I am new to linux.
I downloaded and followed your instructions to install dislocker.
I was able to mount the drive without error, but then I don't have permission to access the folder.
Here are the commands I ran after installation:
sudo mkdir /mnt/tmp
sudo mkdir /mnt/bitlocker
sudo dislocker -v -V /dev/sda1 -u  -- /mnt/tmp/
(entered password) 
sudo mount -o loop,ro /mnt/tmp/dislocker-file /mnt/bitlocker/

I don't get any errors other than "permission denied" when I try to access the "bitlocker" folder.
Please help.
Thanks!
Diarch77

**Comment by Aorimn** [comment]
Hi,
For use with sudo, try `sudo ls /mnt/bitlocker/`.
This is an issue with how fuse deals with permissions. You can pass fuse parameters, using dislocker, after the `--` argument. Basically, if you want your users to be able to access the files without using sudo each time, use something like `-o allow_other` at the end (or at least after the `--` part) of the dislocker command.

**Comment by diarch77** [comment]
Aorimn,
Thank you for the quick response!  I will try this tonight.
Before I do though, can you tell me if this will allow me to see the files using a GUI or just the Terminal?  I am running Raspbian Stretch with Pixel desktop (on a Raspberry Pi3) and I want the main user to be able to see the files on a "Bitlocker" external HDD after using dislocker to mount the drive.
Please let me know if what was posted above will work for this application.
Thanks again!
Dave

**Comment by diarch77** [comment]
Aorimn,
I tried you suggestion above and I can see the files in terminal now but not in the GUI.  How do I get file access via the GUI?
Thanks for your help!
Dave

**Comment by Aorimn** [comment]
I don't see any reason why this would work in the terminal but not in "the GUI" (whatever the GUI you're using): the files permissions are the same, whether you're using the terminal or the GUI.

**Comment by thinrope** [comment]
Not sure how "GUI" works in this case, but there is a chance that it is running under another user, or any of the "automagic" frameworks (e.g. gvfs) not configured properly, or cashing problem...
Anyway, for sure this is NOT dislocker issue.

**Comment by paulstelian97** [comment]
Try mounting with `udisksctl loop-setup --file path/to/mount point/dislocker-file`
That should take care of permissions and let you perform the actual mount from GUI.

**Comment by McPoopyPants** [comment]
Sometimes, and I am using Arch linux, but have tried this in Manjaro as well, you need to just manually type the device path in the directory path.  It doesn't always populate for me, even if it has mounted correctly.  Make sure you ls /mnt/bitlocker/ and you have indeed mounted, then copy the path into your file browser, file explorer, what-have-you, then refresh.  The data should be there, if not maybe try adding a folder inside the mounted drive, like /mnt/bitlocker/Windows/ or whatnot, and refresh.
