### ISSUE TITLE
Unable to find or create trash directory for /home/kk/tr/New Folder/New Folder

### ISSUE THREAD

**Issue by vipzrx** [Aorimn/dislocker#143]
it can creat file ,but can not delete the file in gui

but i can delete in console
➜  New Folder rmdir New\ Folder
➜  New Folder 

![image](https://user-images.githubusercontent.com/5094958/38787380-148ad65e-4160-11e8-8776-5c341889c1c6.png)

**Comment by Aorimn** [comment]
I don't think it's an issue with dislocker, more of something that reads the volume and expect to find a "trash" (which happens to be missing).
