### ISSUE TITLE
dislocker-metadata displays volume name before encryption not current

### ISSUE THREAD

**Issue by gsgrippal** [Aorimn/dislocker#144]
dislocker-metadata displays the volume name in the section `Datum n°1 information`, in the line `[INFO] UTF-16 string: 'PC-NAME VOLUME NAME DATE'`. The problem is, that if you go to windows and change the volume name, dislocker-metadata still displays the original name, the one before encrypton. Is this a bug of dislocker or is how Microsoft Bitlocker works, so there are two labels, one which represents the name before encryption and the other the one after that?

Is is possible to read the current volume name in case it's working properly?

**Comment by Aorimn** [comment]
The volume name in the BitLocker metadata is created when the volume is encrypted, but not changed when the real volume's name is.
If you want to read the real current volume name, you'll need to first decrypt the volume, then read the right NTFS part.

As this isn't a bug in dislocker, I'm closing this issue. However, feel free to ask any question here regarding this issue.

**Comment by gsgrippal** [comment]
Ok thanks, then I understand that for there are two volume names when it's encrypted. i guess both should be available for third party tools like fdisk, blkid, lsblk?

**Comment by gsgrippal** [comment]
I guess that could also be a "bug" or privacy issue, because you can see the prior-to-encryption volume name, which I'm not sure Microsoft wants that...

**Comment by Aorimn** [comment]
Regarding the use of fdisk/blkid/lsblk, if there's any chance for them to show the current volume name, it would have to be run on the decrypted volume: that's plain NTFS and they should be able to perform their parsing on that.

Regarding the potential "bug", bear in mind that what dislocker-metadata shows as the volume name is in clear-text in the bitlocker's metadata (you don't even pass credentials to dislocker-metadata), so Microsoft is actually wanting that: you could get it with hexdump with the right offset.

**Comment by gsgrippal** [comment]
I'm not so sure they left it in plain text intentionally, but probably for a backwards compatibility reason, or they just didn't notice.
But anyway, at least it's not related with data loss issues so not the biggest deal.
