### ISSUE TITLE
Bus error on arm

### ISSUE THREAD

**Issue by JayBitron** [Aorimn/dislocker#145]
Running dislocker on arm device gives "Bus error", no more info is shown, I tested with binary from debian tested with both armel and armhf on a armv7l device, compiled one my self, it's the same. Running on a random partition gives something like "Mon Apr 30 12:33:08 2018 [CRITICAL] Cannot parse volume header. Abort." but when the partition has a valid bitlocker on, it gives "Bus error", I assume it has to do something with memset.

**Comment by Aorimn** [comment]
I've never tested dislocker on any arm platform, I'm not entirely sure how I can even help you on this.
However, why would you think it has something to do with memset?

**Comment by Nable80** [comment]
Hi!
Most ARM implementations don't allow mis-aligned memory accesses. AFAIR, if you attempt such an access the application would be killed with SIGBUS. But there's no need for guessing, just run the application under gdb and post the output of ```i r``` and ```bt``` commands when it crashes. Like this:
```
$ gdb --args ./this-app some args
(gdb) run
... application runs and then crashes ...
(gdb) i r
... values of registers are printed ...
(gdb) bt
... here goes the stack trace ...
```

**Comment by JayBitron** [comment]
I assumed it had something to do with memset or something like due to buss error, on the advice, gdb, I gave it another shot today, but I also changed the cable, this time it works like charm!!! so sorry to bother, that was my mistake.

**Comment by Aorimn** [comment]
Oh, nice to know it works on ARM then, thanks!

**Comment by p3t3r5** [comment]
I have the same error. My old discs work but newly encrypted discs don't work. Tried with Segate 16TB, WD 16TB and old WD 2TB.

`
(gdb) run
Starting program: /usr/bin/dislocker /dev/sda2 -uXXXXXXXX /media/media-bitlocker
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".

Program received signal SIGBUS, Bus error.
0x0000000000000bcf in ?? ()
(gdb) i r
x0             0x4                 4
x1             0x5555569964        366503958884
x2             0xbcf               3023
x3             0x0                 0
x4             0x5                 5
x5             0x1                 1
x6             0x1                 1
x7             0x7ff7da2a68        549619116648
x8             0x101010101010101   72340172838076673
x9             0xffffff80ffffffe8  -545460846616
x10            0x1                 1
x11            0x7fffffec98        549755808920
x12            0x0                 0
x13            0x0                 0
x14            0x7fffffde          2147483614
x15            0x7ff7e53680        549619840640
x16            0x7ff7f6ae38        549620985400
x17            0x7ff7f4b21c        549620855324
x18            0x4f                79
x19            0x5555569964        366503958884
x20            0x4                 4
x21            0x5555569964        366503958884
x22            0x5555569844        366503958596
x23            0x7ff7f53c88        549620890760
x24            0x7ffffff288        549755810440
x25            0x7ffffff338        549755810616
x26            0x0                 0
x27            0x0                 0
x28            0x0                 0
x29            0x7ffffff220        549755810336
x30            0x7ff7f4bc0c        549620857868
sp             0x7ffffff220        0x7ffffff220
pc             0xbcf               0xbcf
cpsr           0x80000000          [ EL=0 N ]
fpsr           0x0                 0
fpcr           0x0                 0
(gdb) bt
#0  0x0000000000000bcf in ?? ()
#1  0x0000007ff7f4bc0c in print_one_datum () from /usr/lib/libdislocker.so.0.7
#2  0x0000007ff7f4bf7c in print_datum_vmk () from /usr/lib/libdislocker.so.0.7
#3  0x0000007ff7f4bc0c in print_one_datum () from /usr/lib/libdislocker.so.0.7
#4  0x0000007ff7f4e9f0 in print_data () from /usr/lib/libdislocker.so.0.7
#5  0x0000007ff7f4d070 in dis_metadata_initialize () from /usr/lib/libdislocker.so.0.7
#6  0x0000007ff7f497a4 in dis_initialize () from /usr/lib/libdislocker.so.0.7
#7  0x000000555555649c in main ()
(gdb) 
`

**Comment by gabrielssanches** [comment]
@p3t3r5 just use tag v0.7.2, works perfectly
