### ISSUE TITLE
Compilation error with a fresh Ubuntu 18.04 LTS (Bionic)

### ISSUE THREAD

**Issue by Tux-Panik** [Aorimn/dislocker#148]
Hi,
Following the installation instructions, my fresh Ubuntu 18.04 raised a compilation error related to Ruby:
`user@host:/opt/dislocker$ sudo cmake .`
`-- The C compiler identification is GNU 7.3.0`
`-- Check for working C compiler: /usr/bin/cc`
`-- Check for working C compiler: /usr/bin/cc -- works`
`-- Detecting C compiler ABI info`
`-- Detecting C compiler ABI info - done`
`-- Detecting C compile features`
`-- Detecting C compile features - done`
`-- Found POLARSSL: /usr/include  `
`PolarSSL/mbedTLS version: 2.8.0`
`-- Found FUSE: /usr/include  `
`-- Configuring done`
`-- Generating done`
`-- Build files have been written to: /opt/dislocker`

`user@host:/opt/dislocker-master$ sudo make`
`Scanning dependencies of target dislocker`
`[  2%] Building C object src/CMakeFiles/dislocker.dir/dislocker.c.o`
`In file included from /usr/include/ruby-2.5.0/ruby.h:33:0,`
`                 from /opt/dislocker/include/dislocker/ruby.h:35,`
`                 from /opt/dislocker/include/dislocker/accesses/accesses.h:38,`
`                 from /opt/dislocker/src/dislocker.c:36:`
`/usr/include/ruby-2.5.0/ruby/ruby.h:24:10: fatal error: ruby/config.h: No such file or directory`
` #include "ruby/config.h"`
`          ^~~~~~~~~~~~~~~`
`compilation terminated.`
`src/CMakeFiles/dislocker.dir/build.make:62: recipe for target 'src/CMakeFiles/dislocker.dir`
`/dislocker.c.o' failed`
`make[2]: *** [src/CMakeFiles/dislocker.dir/dislocker.c.o] Error 1`
`CMakeFiles/Makefile2:200: recipe for target 'src/CMakeFiles/dislocker.dir/all' failed`
`make[1]: *** [src/CMakeFiles/dislocker.dir/all] Error 2`
`Makefile:129: recipe for target 'all' failed`
`make: *** [all] Error 2`

I would say that issue is related to ruby version, but I didn't found any workaround.
If you have an idea...
Thanks in advance,
Regards,
Julien

**Comment by Aorimn** [comment]
You could apply the modifications proposed in the PR #146. I've not had the time to test it properly, but I don't see anything that'll not work specifically on Ubuntu 18.04.

**Comment by Tux-Panik** [comment]
The following command fixed the issue:
sudo cp /usr/include/x86_64-linux-gnu/ruby-2.5.0/ruby/config.h /usr/include/ruby-2.5.0/ruby/

Thanks for the feedback. 
Regards, 
Julien
