### ISSUE TITLE
Ruby error on  make step 

### ISSUE THREAD

**Issue by Adamandinos** [Aorimn/dislocker#150]
Hello i have followed the instructions and everything went through until i hit make after compiling and gives me this error -

Fatal error: ruby/config.h No such file or dir
#include"ruby/config.h" 
compilation terminated

Any ideas guys?

**Comment by Aorimn** [comment]
Hi, either you're missing the ruby headers, or you're on Ubuntu 18.04. For the latter, please apply the patch from #146. It isn't good enough to be merged but seems to work like a charm.

**Comment by Adamandinos** [comment]
Thank you for the quick response, i am on latest Kali version, where can i get get the ruby headers ?

**Comment by wade-welles** [comment]
This issue still exists in Debian
