### ISSUE TITLE
Very slow write speed on raspbian pi

### ISSUE THREAD

**Issue by WOo0W** [Aorimn/dislocker#152]
Hi, I get very slow write speed (600-800KB/s) when using dislocker to mount the mobile hard disk to /ftp/f
Read is ok (30MB/s)
`dislocker -v -V /dev/sda4 -p -- /data`
`mount -t ntfs-3g -o uid=root,gid=root,umask=022 /data/dislocker-file /ftp/f/`
![image](https://user-images.githubusercontent.com/24245520/41137833-f49e16ce-6b0f-11e8-97b5-bf813b0e8982.png)
CPU usage when writing:
![image](https://user-images.githubusercontent.com/24245520/41137935-a774e4b2-6b10-11e8-8b7f-741d01a8c26d.png)

**Comment by paulstelian97** [comment]
Maybe have the reads of the device be buffered in Dislocker? Or is it possible to avoid a read-modify-write cycle? Because I'm not sure what else could cause such a performance impact.

**Comment by Aorimn** [comment]
Probably linked to https://github.com/Aorimn/dislocker/issues/138, see more specifically https://github.com/Aorimn/dislocker/issues/138#issuecomment-729170152
