### ISSUE TITLE
Very high CPU load while writing

### ISSUE THREAD

**Issue by ereb-thanatos** [Aorimn/dislocker#157]
First off, thank you @Aorimn for this great project! I am using it on an Archlinux machine and it works like a charm.

...except for the fact that I get an incredibly high CPU usage while moving data from or to the mounted volume. Htop output looks similar to [Issue 152: Very slow write speed on raspbian pi](https://github.com/Aorimn/dislocker/issues/152), and the CPU temperature gets over 80°C on my i7-8750H. However, I still get 50 MB/s write and 320 MB/s read speeds. Both Arch and Win partitions are on the same NVMe SSD.

![screenshot](https://user-images.githubusercontent.com/19406681/46079900-baebb780-c198-11e8-9071-b30c7ebee039.png)
```
System info:
  Linux version 4.18.8-arch1-1-ARCH
  dislocker 0.7.1, compiled for Linux/x86_64 from master:cad6494

Commands:
  dislocker -q --volume /dev/nvme0n1p4 --recovery-password=XXX -- /tmp/dislocker
  mount -t ntfs-3g -o rw,dmask=0077,fmask=0177,uid=1000,gid=1000 /tmp/dislocker/dislocker-file /mnt/windows
```

Thank you, and let me know if you need any additional info.

**UPD:** There is a simple solution for dislocker-file: Increasing the defined constant `NB_READ_SECTOR` from 16 to a much bigger value (e.g. 65536) achieves more performance (+75% read speed in my case) with less cpu load. No such luck for dislocker-fuse, though... Seems that the problem would be on the FUSE end.

**Comment by ereb-thanatos** [comment]
Same behaviour in [dislocker-git](https://aur.archlinux.org/packages/dislocker-git/) (compiled version: master:747cbd6).

**Comment by akuropka** [comment]
I want to give my comments here as well just for reference...
RPi3 4.19.114-1-ARCH USB Bitlocker drive mounted with fuse
read speed seems ok, writting speed in the beginning as well but goes then down to a bit over 4 MB/s.
While the idea is great and implementation seamless it's practically not interesting, unfortunately.

![20200419-133636](https://user-images.githubusercontent.com/22570574/79687058-e6d00180-8244-11ea-9c81-6c1b66f8ad6c.png)
![20200419-134558](https://user-images.githubusercontent.com/22570574/79687066-e9caf200-8244-11ea-9493-3f88be180199.png)
![20200419-134005](https://user-images.githubusercontent.com/22570574/79687069-ec2d4c00-8244-11ea-960a-45e0954b67d5.png)

**Comment by laggingreflex** [comment]
> NB_READ_SECTOR

This is found in the file `src/dislocker-file.c` which means it'll need to be (re-)compiled, right? 

Any chance this could be set any other way, like via an environment variable?

I found similar response [on reddit][1] with another suggestion to modify the `NB_THREAD` variable in `src/inouts/sectors.c` and luckily for that variable there's a note there that says:

> Use the environment variable FUSE_MAX_WORKERS to change the FUSE's threads number.

Would be brilliant if all these settings could've been modified via flags or environment variables...

---

Also, are there any side effects to modifying these values? Like higher risk of data loss in unexpected shutdown?

[1]: https://www.reddit.com/r/linuxquestions/comments/l9gk0z/encrypt_all_3_of_my_partitions/gljbox0/
