### ISSUE TITLE
run dislocker after plug usb stick with bitlocker partition in

### ISSUE THREAD

**Issue by mttkrb** [Aorimn/dislocker#159]
Hi,
is it possible to open a popup-window to enter the encryption password and automatically mount the device? 
Actually I have to run dislocker on e.g. /dev/sde1 as root and then mount the ntfs partition in another folder. 
It would be a nice feature to perform this without root-access  for removeable media like a normal usb stick or sd-card.

**Comment by mhogomchungu** [comment]
zuluCrypt is a Qt based GUI and it now supports unlocking bitlocker volume using its GUI.

https://github.com/mhogomchungu/zuluCrypt/issues/109

**Comment by Aorimn** [comment]
Thanks @mhogomchungu, closing this now
