### ISSUE TITLE
[ERROR] The sector size found is null.

### ISSUE THREAD

**Issue by a-roussanov** [Aorimn/dislocker#160]
Hello, 

I have tried to search for solution but I did not find any for the issue I am experiencing. I am trying to use dislocker to open a BitLocker encrypted USB key - I have both the password and the recovery key.

"fdisk -l /dev/sdb" gives the following:
Disk /dev/sdb: 3.8 GiB, 4009754624 bytes, 7831552 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x0a9a1b1a

Device     Boot Start     End Sectors  Size Id Type
/dev/sdb1        2048 7831551 7829504  3.8G  7 HPFS/NTFS/exFAT
------

dislocker -vvv -r -V /dev/sdb1 -u -- /mnt/ntfs
Wed Oct 10 16:09:08 2018 [INFO] dislocker by Romain Coltel, v0.7.1 (compiled for Linux/x86_64)
Wed Oct 10 16:09:08 2018 [INFO] Compiled version: :
Wed Oct 10 16:09:08 2018 [ERROR] The sector size found is null.
Wed Oct 10 16:09:08 2018 [CRITICAL] Cannot parse volume header. Abort.

-----
dislocker-fuse -vvv -r -V /dev/sdb -o $((2048 * 512)) -u -- /mnt/ntfs
Wed Oct 10 16:09:50 2018 [INFO] dislocker by Romain Coltel, v0.7.1 (compiled for Linux/x86_64)
Wed Oct 10 16:09:50 2018 [INFO] Compiled version: :
Wed Oct 10 16:09:50 2018 [ERROR] The signature of the volume (��������) doesn't match the BitLocker's ones (-FVE-FS- or MSWIN4.1). Abort.
Wed Oct 10 16:09:50 2018 [CRITICAL] Cannot parse volume header. Abort.
----

I get the same output when using without -o. Inputting the password on the command line after -u does not change anything.

dislocker-metadata -vvv -V /dev/sdb1
Wed Oct 10 16:11:22 2018 [DEBUG] Verbosity level to DEBUG (4) into 'stdout'
Wed Oct 10 16:11:22 2018 [INFO] dislocker by Romain Coltel, v0.7.1 (compiled for Linux/x86_64)
Wed Oct 10 16:11:22 2018 [INFO] Compiled version: :
Wed Oct 10 16:11:22 2018 [DEBUG] Trying to open '/dev/sdb1'...
Wed Oct 10 16:11:22 2018 [DEBUG] Trying to open '/dev/sdb1'...
Wed Oct 10 16:11:22 2018 [DEBUG] Opened (fd #3).
Wed Oct 10 16:11:22 2018 [DEBUG] New memory allocation at 0x55fde04af940 (0x18 bytes allocated)
Wed Oct 10 16:11:22 2018 [DEBUG] New memory allocation at 0x55fde04af960 (0x90 bytes allocated)
Wed Oct 10 16:11:22 2018 [DEBUG] New memory allocation at 0x55fde04afa00 (0x200 bytes allocated)
Wed Oct 10 16:11:22 2018 [DEBUG] Positioning #3 at offset 0 from 0
Wed Oct 10 16:11:22 2018 [DEBUG] Reading volume header...
Wed Oct 10 16:11:22 2018 [DEBUG] Reading 0x200 bytes from #3 into 0x55fde04afa00
Wed Oct 10 16:11:22 2018 [DEBUG] Volume header read
Wed Oct 10 16:11:22 2018 [DEBUG] =====[ Volume header informations ]=====
Wed Oct 10 16:11:22 2018 [DEBUG]   Signature: '-FVE-FS-'
Wed Oct 10 16:11:22 2018 [DEBUG]   Sector size: 0x0000 (0) bytes
Wed Oct 10 16:11:22 2018 [DEBUG]   Sector per cluster: 0x00 (0) bytes
Wed Oct 10 16:11:22 2018 [DEBUG]   Reserved clusters: 0x0000 (0) bytes
Wed Oct 10 16:11:22 2018 [DEBUG]   Fat count: 0x00 (0) bytes
Wed Oct 10 16:11:22 2018 [DEBUG]   Root entries: 0x0000 (0) bytes
Wed Oct 10 16:11:22 2018 [DEBUG]   Number of sectors (16 bits): 0x0000 (0) bytes
Wed Oct 10 16:11:22 2018 [DEBUG]   Media descriptor: 0x00 (0) bytes
Wed Oct 10 16:11:22 2018 [DEBUG]   Sectors per fat: 0x0000 (0) bytes
Wed Oct 10 16:11:22 2018 [DEBUG]   Hidden sectors: 0x00000000 (0) bytes
Wed Oct 10 16:11:22 2018 [DEBUG]   Number of sectors (32 bits): 0x00000000 (0) bytes
Wed Oct 10 16:11:22 2018 [DEBUG]   Number of sectors (64 bits): 0x0000000000000000 (0) bytes
Wed Oct 10 16:11:22 2018 [DEBUG]   MFT start cluster: 0x0000000000060001 (393217) bytes
Wed Oct 10 16:11:22 2018 [DEBUG]   Metadata Lcn: 0x0000000000000000 (0) bytes
Wed Oct 10 16:11:22 2018 [DEBUG]   Volume GUID: '4967D63B-2E29-4AD8-8399-F6A339E3D001'
Wed Oct 10 16:11:22 2018 [DEBUG]   First metadata header offset:  0x0000000002100000
Wed Oct 10 16:11:22 2018 [DEBUG]   Second metadata header offset: 0x0000000051058000
Wed Oct 10 16:11:22 2018 [DEBUG]   Third metadata header offset:  0x000000009ffb0000
Wed Oct 10 16:11:22 2018 [DEBUG]   Boot Partition Identifier: '0xaa55'
Wed Oct 10 16:11:22 2018 [DEBUG] ========================================
Wed Oct 10 16:11:22 2018 [ERROR] The sector size found is null.
Wed Oct 10 16:11:22 2018 [CRITICAL] Cannot parse volume header. Abort.
Wed Oct 10 16:11:22 2018 [CRITICAL] Can't initialize dislocker. Abort.

I am really not sure what to do next. Any help would be greatly appreciated.

Many thanks in advance

**Comment by pspathis** [comment]
Hi
I get the same mistake trying to decrypt an exFat SD card. Did you manage to solve this issue ?
thx

**Comment by solsav** [comment]
same problem over here.. 
```
Fri Apr 17 18:04:14 2020 [DEBUG] =====[ Volume header information ]=====
Fri Apr 17 18:04:14 2020 [DEBUG]   Signature: '-FVE-FS-'
Fri Apr 17 18:04:14 2020 [DEBUG]   Sector size: 0x0000 (0) bytes
Fri Apr 17 18:04:14 2020 [DEBUG]   Sector per cluster: 0x00 (0) bytes
Fri Apr 17 18:04:14 2020 [DEBUG]   Reserved clusters: 0x0000 (0) bytes
...
Fri Apr 17 18:04:14 2020 [ERROR] The sector size found is null.
Fri Apr 17 18:04:14 2020 [CRITICAL] Cannot parse volume header. Abort.
```

**Comment by parduhn** [comment]
same here.

**Comment by scottzach1** [comment]
Bump, did you guys manage to find any solution? :)

**Comment by Aorimn** [comment]
Sector size has been sorted out in the latest dislocker version, v0.7.3 (thanks to @haobinnan), so I'm going to close this one. Feel free to reopen with comments.
