### ISSUE TITLE
Password problem

### ISSUE THREAD

**Issue by Lockdis** [Aorimn/dislocker#164]
Hello, i have lost the recovery key of one of my 2 bitlocked disks, i have managed to decrypt my other disk using his recoverykey and i was trying to unlock my other hdd using his password it don't use tpm, just plain password.i have tried my 2 password because not sure which one is for which hdd

```
[me@ok ~]$ sudo dislocker -r -v -V /dev/sda2 -uor=°*ù$KIUrge'"79"gytj@&==fregf*  -- /mnt/bitlocker2
> 
> 
> 
[me@ok ~]$ sudo dislocker -r -v -V /dev/sda2 -up$£*%!gmlpoegàèé#&@F987tyjtY56  -- /mnt/bitlocker2
bash: !gmlpoegàèé#: event not found
```
 first command is doing nothing but is stuck waiting and the 2nd is returning  event not found error probably because for the % char.
i have tried to put the password in quotes ' and even tried using \ to escape special chars but nothing is working, any idea how to solve this? thanks

Edit,  i have tried with 

```
[me@ok ~]$ sudo dislocker -r -v -V /dev/sda2 -uor=°*ù$KIUrge\'"79"gytj@\&==fregf*  -- /mnt/bitlocker2
[me@ok ~]$ sudo dislocker -r -v -V /dev/sda2 -up$£*%\!gmlpoegàèé#\&@F987tyjtY56  -- /mnt/bitlocker2
```

it's working now but it return me incorrect password while the password is correct
`None of the provided decryption mean is decrypting the keys. Abort.
`

**Comment by paulstelian97** [comment]
Have you tried quoting the passwords so the shell doesn't interpret the stars?
Also, I think Dislocker doesn't work properly with non-ASCII characters in the password, not yet at least.

**Comment by Lockdis** [comment]
i have found my recovery code
