### ISSUE TITLE
High cpu usage while syncing onedrive

### ISSUE THREAD

**Issue by rednag** [Aorimn/dislocker#166]
According to https://github.com/abraunegg/onedrive/issues/347

I've my SD card encypted by BitLocker and mounting it in Ubuntu 18.04 via dislocker. This SD card is used as OneDrive-storage unit. 

While OneDrive is syncing the process is due to high read/write tasks around 25% all the time, so abraunegg said this issue occurs because I'm synching on an encrypted SD card through dislocker mount.

Maybe you can fix it?!

**Comment by Aorimn** [comment]
This is indeed a recurring issue with dislocker, maybe due to fuse, maybe to the way encryption is implemented. This is unfortunately a hard issue to fix right now.

**Comment by Aorimn** [comment]
The v0.7.3 version should improve this, probably not fix it entirely. I'll close this as more than one issue is opened for this case.
