### ISSUE TITLE
bash: /usr/bin/dislocker: No such file or directory

### ISSUE THREAD

**Issue by ghost** [Aorimn/dislocker#173]
When I hit tab after I type "dislocker" in a terminal window:

```
****@*********:~/.makeinstall/dislocker$ dislocker
dislocker           dislocker-file      dislocker-fuse
dislocker-bek       dislocker-find      dislocker-metadata
```

Here, we see that all of these packages are installed. They all work as intended, except for the base package:

```
****@*********:~/.makeinstall/dislocker$ dislocker
bash: /usr/bin/dislocker: No such file or directory
```

The software still works - all but the base package.

**Comment by Aorimn** [comment]
Not sure how you installed dislocker, but you have every needed binary.

I guess "dislocker" should only be a symbolic link to dislocker-fuse, which is the not found thing. Can you run the following commands:
```bash
$ readlink /usr/bin/dislocker
$ ls -l `readlink /usr/bin/dislocker`
```

**Comment by paulstelian97** [comment]
Maybe it's a runtime linker error, they manifest the same. Can you run `ldd /usr/bin/dislocker`? Sorry for posting to an old issue.
