### ISSUE TITLE
Feature request: encrypt and decrypt drives

### ISSUE THREAD

**Issue by superbonaci** [Aorimn/dislocker#18]
Be able to encrypt and decrypt drives.

**Comment by Aorimn** [comment]
> About encrypting the drive with dislocker: not possible yet.
About decrypting it: yes it's possible but not on the fly like Windows does. I mean directly decrypting the drive to itself, without having to extract the contents, reformat and write back.

I would welcome any work on this, but won't have time to work on this myself.

**Comment by superbonaci** [comment]
So closing for now since it's not a bug.
