### ISSUE TITLE
forget passord of bitlocker and I lost my recovery key

### ISSUE THREAD

**Issue by kingalilok** [Aorimn/dislocker#181]
forget passord of bitlocker and I lost my recovery key 
if anyone can help wiith it plz

**Comment by Aorimn** [comment]
Unfortunately, nothing can easily be done for you, dislocker isn't a password-cracking tool.

**Comment by kingalilok** [comment]
if there any way to rocovry my life from dick without open it ??

‫في الخميس، 13 يونيو 2019 في 1:18 م تمت كتابة ما يلي بواسطة ‪Aorimn‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Aorimn** [comment]
Not that I know of

**Comment by openffchrome** [comment]
if it was loggued intoms account the recovery key in accessible from the account webpage
