### ISSUE TITLE
Not building on Mac OS

### ISSUE THREAD

**Issue by jickler** [Aorimn/dislocker#193]
I'm not entirely sure what I'm doing, so I apologize if this isn't a real bug -- feel free to delete this issue if appropriate. I would like to build dislocker on mac to take advantage of recent commits. I can successfully compile 0.7.1, but when I try to build the live version, I always get this fail: 

`/Users/noneofya/Downloads/dislockertry3/dislocker/src/metadata/metadata.c:167:31: error: use of undeclared identifier 'BLKSSZGET'
                ioctl(dis_meta_cfg->fve_fd, BLKSSZGET, &nSectorSize);
                                            ^
`

Complete build log: https://pastebin.com/tgCfjKXP

**Comment by haobinnan** [comment]
please try: https://github.com/haobinnan/dislocker

**Comment by haobinnan** [comment]
@jickler I do not have Mac OS and cannot test it. You can test and try it on your own: https://github.com/haobinnan/dislocker

**Comment by Aorimn** [comment]
A new version is out, v0.7.3, and fixes this issue.
