### ISSUE TITLE
new release/tag?

### ISSUE THREAD

**Issue by mhogomchungu** [Aorimn/dislocker#194]
The last one was in 2017 and these has been significant changes since then.

**Comment by h-vetinari** [comment]
Along the same lines: it would also be nice to have a passing CI again. :)

**Comment by mhogomchungu** [comment]
Why is it failing?

**Comment by h-vetinari** [comment]
Under [commits](https://github.com/Aorimn/dislocker/commits/master), I saw the red X indicating a failed CI - following that link leads to [the travis job overview](https://travis-ci.org/Aorimn/dislocker/builds/563891139?utm_source=github_status&utm_medium=notification), but I didn't check any further than that.

**Comment by colemickens** [comment]
I'd like to be able to update `dislocker` in nixpkgs for Nix/NixOS users, but I'm reluctant to do so without a tagged release. At the same time, my understanding is that HEAD is needed for recent Windows 10 BitLocker-d devices... so I'm tempted to go ahead and push it in soon. Thank you for this tool and the maintenance of it!

**Comment by nextgenthemes** [comment]
@colemickens Why is the latest version needed for recent win10 devices? I am using bitlocker for years with my win10 partitition but recently the partition is only mounted as read only. I changed nothing about the config and my win10 fast boot is still disabled but for some reason its only mounted as read only.

I think I try to build and latest version and check if it works again but may also have something to do with my always updated SUSE Tumbleweed install.

**Comment by Aorimn** [comment]
Hi, a v0.7.3 tag has been pushed and should fix those issues.
