### ISSUE TITLE
Can't mount FAT32 disk encrypted with dislocker

### ISSUE THREAD

**Issue by superbonaci** [Aorimn/dislocker#20]
The pendrive was formated to FAT32 under windows 7 and then encrypted.
root@kali:~# dislocker -v -V /dev/sdd1 -uAAbb.111 -- /mnt/bitlocker -d
Wed Aug 20 21:48:56 2014 [CRITICAL] The signature of the volume (MSWIN4.1) doesn't match the BitLocker's one (-FVE-FS-). Abort.

With NTFS works.

**Comment by Aorimn** [comment]
The develop branch generates a working binary for FAT32-encrypted.
