### ISSUE TITLE
 Decipher certain sector of a file 

### ISSUE THREAD

**Issue by stackoverflowembedded** [Aorimn/dislocker#203]
Hello everybody,
I'm trying to decipher certain sector of a file that I know his sections on the hard drive, I just want a specific one sector from the file. I have the password of the BitLocker.
How can parts of Dislocker be best used to decrypt a particular sector?
Thank you all
Em.

**Comment by Aorimn** [comment]
Hi, you can run dislocker-fuse to mount the encrypted volume (e.g. `dislocker-fuse -V/dev/sda3 /mnt/dislocker`) and expose an unencrypted volume (`/mnt/dislocker/dislocker-file` in this example), which is shown as a plain file. This plain file can be sought through, so you can then use any tool to read this sector in the file (which will be named `dislocker-file`), e.g. with dd: `dd if=/mnt/dislocker/dislocker-file ...`
