### ISSUE TITLE
bug dislocker fedora 31/windows 10 build 1909

### ISSUE THREAD

**Issue by cedempereur** [Aorimn/dislocker#206]
Hello,
I installed dislocker on fedora 31 to activate disks from windows 10 build 1909
but I have a mount problem after the command: sudo dislocker -r -V / dev / sdaX -uPASSWORD - / media / bitlocker. This tells me "segmentation error" so no way to continue. Thank you for helping me.

**Comment by haobinnan** [comment]
https://github.com/Aorimn/dislocker/issues/185

**Comment by cedempereur** [comment]
Thank you

**Comment by mimi9393** [comment]
Hello same issue and i cloned the dislocker on your page @haobinnan still segmentation fault pls help

**Comment by florentlagoda** [comment]
Hi, Same for me :(

**Comment by AxolotlMX** [comment]
Same here on Linux Mint 19.3, cloned and built it from the aforementioned repo and still get the same error, has anyone found a way to make it work?

**Comment by AxolotlMX** [comment]
I was wrong, it totally works following these instructions! Thanks <3

https://github.com/Aorimn/dislocker/issues/185#issuecomment-570794684

**Comment by haobinnan** [comment]
bug fixed: https://github.com/haobinnan/dislocker

**Comment by florentlagoda** [comment]
possible to have this version in ubuntu repository ?

**Comment by Aorimn** [comment]
Hi, a v0.7.3 tag has been pushed and should fix those issues.

**Comment by cedempereur** [comment]
Thank you very much but i have already made the fix.Best regardsEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Aorimn <notifications@github.com> Date : 17/11/2020  22:29  (GMT+01:00) À : Aorimn/dislocker <dislocker@noreply.github.com> Cc : cedempereur <cedric.lecocq@aliceadsl.fr>, Author <author@noreply.github.com> Objet : Re: [Aorimn/dislocker] bug dislocker fedora 31/windows 10 build 1909 (#206) 
Hi, a v0.7.3 tag has been pushed and should fix those issues.
