### ISSUE TITLE
Dislocker can't find a BitLocker volume, but hexdump shows "FVE-FS" flag?

### ISSUE THREAD

**Issue by kennbr34** [Aorimn/dislocker#209]
A friend of mine got a boot error with his Windows 10 install and I'm trying to help him backup his files with Linux.  However, I can't seem to access the partition, and the partition table just says "Microsoft basic data", though he says it should be NTFS.  Through a bunch of Google searches I found that this is likely to mean it is encrypted with BitLocker, so I tried running dislocker on it, and got the error "Signature does not match BitLocker's ones".  So I tried running dislocker-finder and it said it found no volumes.

However, using hexdump, I can see the "FVE-FS" flag and a line slightly above saying "bitlocker".  Here's a pastebin of the portion of the dump, the "FVE-FS" flag is at offset 067f4170 three lines up from the bottom.
https://pastebin.com/ETs5WEUx

So I'm wondering if this may be a false-negative with dislocker saying it's not a BitLocker volume or what else may be going on?

**Comment by Aorimn** [comment]
The "FVE-FS" partition signature is used to mark the beginning of a BitLocker partition. However, the dump where you're seeing the"FVE-FS" string doesn't seem to be the beginning of the partition (it looks like clear-text strings to me).

Using `hexdump -C -n 16 /dev/sd*` will give you the first 16 bytes of every disk and partition. If you see the "FVE-FS", then it's probably the one you're looking for.

As it stands, it doesn't seem to be a dislocker issue, so I'm closing the issue.
