### ISSUE TITLE
Install on Ubuntu 19 error

### ISSUE THREAD

**Issue by joetaras** [Aorimn/dislocker#210]
When I try to install dislocker on Ubuntu 19 with this string:

`sudo apt-get install gcc make libfuse-dev libmbedtls-dev ruby-dev`

I've got this error: `Unable to locate package libmbedtls-dev`

**Comment by Aorimn** [comment]
Looks like (it does exist)[https://launchpad.net/ubuntu/disco/+package/libmbedtls-dev], maybe try to update your index before: `apt update && apt install libmbedtls-dev`
