### ISSUE TITLE
Aorimn vs haobinnan dislocker versions

### ISSUE THREAD

**Issue by superbonaci** [Aorimn/dislocker#214]
Is there any real difference between Aorimn's version and [haobinnan's one](https://github.com/haobinnan/dislocker)? Are you merging bugfixes and updates from there? Which one is the original developer?

**Comment by AndrewL2018** [comment]
@superbonaci

![image](https://user-images.githubusercontent.com/43220610/90283045-4ec5db80-de24-11ea-9dd2-b345baf26b90.png)

**Comment by superbonaci** [comment]
What are the advantages, newer bugfixes?

**Comment by Aorimn** [comment]
haobinnan's patches have been integrated into this repository, a new version has been tagged (v0.7.3). I'm closing this :)

**Comment by superbonaci** [comment]
Thanks a lot!
