### ISSUE TITLE
Read-only file system

### ISSUE THREAD

**Issue by louisabraham** [Aorimn/dislocker#215]
I'm trying to mount a bitlocker encrypted USB drive (manjaro)

```
sudo mkdir /run/media/bitlocker
sudo mkdir /run/media/mount

sudo dislocker -r -V /dev/sda1 -upassword -- /run/media/bitlocker
sudo mount -o loop,rw /run/media/bitlocker/dislocker-file /run/media/mount
```

`ls /run/media/mount` works perfectly (it shows me the files from windows).

However, I cannot write to the volume.

```
$ touch /run/media/mount/hello
touch: cannot touch '/run/media/mount/hello': Read-only file system
```

**Comment by Aorimn** [comment]
It looks like you're using `-r` which stands for read-only in dislocker's commandline, hence your error.
