### ISSUE TITLE
commit f778706e72d9f7bac84a5a4cd37f0b56cebdef49 is not worked for osx 10.15.4

### ISSUE THREAD

**Issue by Cruise-Yan** [Aorimn/dislocker#216]
this commit use mount.h, but this is not work on osx 10.15.4, there is not define  BLKSSZGET and BLKGETSIZE64

**Comment by haobinnan** [comment]
Try: https://github.com/haobinnan/dislocker

**Comment by Cruise-Yan** [comment]
Yes, it does fix this issue, Thanks !!
but there is other two problems:
1. CMAKE_C_COMPILER is /Library/Developer/CommandLineTools/usr/bin/cc, this compiler doesn't contain the headers in /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
2. src/CMakeFiles/dislocker-fuse.dir/link.txt, there is not contains lib /usr/local/lib

my os is upgrade from 10.14 to 10.15, and compile dislocker on 10.15

**Comment by Aorimn** [comment]
Version 0.7.3 has fixed this issue, thanks @haobinnan
