### ISSUE TITLE
Cannot mount dislocker-file on Ubuntu Focal Fossa 

### ISSUE THREAD

**Issue by entodoays** [Aorimn/dislocker#217]
After upgrading to Focal Fossa I lost access to the Bitlocker encrypted Windows partition. I checked and the dislocker package is still installed; /etc/fstab hasn't changed, the dislocker-file is present. When I try to mount it with `sudo mount -o loop /mnt/OS/dislocker-file /mnt/Windows` I get:

> mount: /mnt/Windows: wrong fs type, bad option, bad superblock on /dev/loop13, missing codepage or helper program, or other error.

My fstab file entries are as follows:

> /dev/nvme0n1p3 /mnt/OS fuse.dislocker recovery-password=myrecoverypassword 0 0 
> /mnt/OS/dislocker-file /mnt/Windows auto nofail,x-gvfs-show,x-gvfs-name=C: 0 0

I checked the logs and am seeing a series of errors on a number of logical blocks:

> blk_update_request: I/O error, dev loop13, sector 469239680 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
> Buffer I/O error on dev loop13, logical block 58654960, async page read

How do I solve this issue?

**Comment by inwwin** [comment]
I get this same error too!

**Comment by entodoays** [comment]
I solved the problem by removing the apt version of dislocker and install from git. See [this post](https://github.com/Aorimn/dislocker/issues/185#issuecomment-570794684)

**Comment by inwwin** [comment]
Great Thanks

**Comment by entodoays** [comment]
Removing the dislocker apt package didn't remove the libdislocker0.7 dependency. Apt is telling me to autoremove this package, but should I?

**Comment by Aorimn** [comment]
Hi, a v0.7.3 tag has been pushed and should fix this issue. However, packages haven't been updated downstream yet.
