### ISSUE TITLE
ld: library not found for -losxfuse_i64 when running make on Mac OS

### ISSUE THREAD

**Issue by AddictArts** [Aorimn/dislocker#218]
Mac OS Mojave

Steps:

```
cmake .
make
```

Output:

```
[ 43%] Built target dislocker
[ 46%] Built target dislocker-bek
[ 46%] Built target dislocker-find
[ 50%] Built target dislocker-file
[ 51%] Linking C executable dislocker-fuse
ld: library not found for -losxfuse_i64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have the libs in /usr/local/lib, see below, ...

```
ls -l /usr/local/lib/libosxfuse_i64.*
lrwxr-xr-x  1 admin  staff  18 May 12 18:20 /usr/local/lib/libosxfuse_i64.2.dylib -> libosxfuse.2.dylib
lrwxr-xr-x  1 admin  staff  16 May 12 18:20 /usr/local/lib/libosxfuse_i64.dylib -> libosxfuse.dylib
lrwxr-xr-x  1 admin  staff  13 May 12 18:20 /usr/local/lib/libosxfuse_i64.la -> libosxfuse.la
```

I am not familiar with cmake and how to adjust the LD_LIBRARY_PATH

Thanks for any help. Cheers

A fix here will likely resolves #53

**Comment by silentbugs** [comment]
Did you find any workarounds for this?

**Comment by AddictArts** [comment]
Wish I did, but no I didn't. I ended up just using a windows 10 install to open the disk.

**Comment by silentbugs** [comment]
You need to set LIBRARY_PATH on your ~/.bash_profile (or ~/.zprofile if using zsh):

```
export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib"
```

**Comment by Aorimn** [comment]
I'm pretty sure it's not a dislocker issue, but I don't have any OSX at hand (except on travis, where the issue doesn't appear) to test it. If I'm wrong, please reopen the issue and advise for a fix.

**Comment by rev111** [comment]
Hello, I'm having the same problem. 
I'm trying to build under OSX Big Sur 11.1 with the new M1/Silicon processor.  
I rely on Macports as package manager and I always read that installing homebrew along it is not recommended. So I'm trying to build from source. 
cmake works with this command on one line:
`LIBRARY_PATH=/usr/local/lib:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib CPATH=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include cmake .`

But make fails:
```
dislocker2 % make
[ 44%] Built target dislocker
[ 47%] Built target dislocker-bek
[ 47%] Built target dislocker-find
[ 50%] Built target dislocker-file
[ 51%] Linking C executable dislocker-fuse
**ld: library not found for -losxfuse_i64**
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/dislocker-fuse] Error 1
make[1]: *** [src/CMakeFiles/dislocker-fuse.dir/all] Error 2
make: *** [all] Error 2
```

The libraries below have been installed by the latest version of OSXFuse (now renamed to MacFuse) 4.0.5. 
Are these the osxfuse libraries that dislocker expects?
```
dislocker2 % ls -la /usr/local/lib/\*fuse\*
-rwxr-xr-x  1 root  wheel  580688  2 Jan 03:54 /usr/local/lib/libfuse.2.dylib
lrwxr-xr-x  1 root  wheel      15  3 Jan 22:53 /usr/local/lib/libfuse.dylib -> libfuse.2.dylib
-rwxr-xr-x  1 root  wheel     971  2 Jan 03:54 /usr/local/lib/libfuse.la
lrwxr-xr-x  1 root  wheel      15  3 Jan 22:53 /usr/local/lib/libosxfuse.2.dylib -> libfuse.2.dylib
lrwxr-xr-x  1 root  wheel      15  3 Jan 22:53 /usr/local/lib/libosxfuse_i64.2.dylib -> libfuse.2.dylib
```

I tried to alter search terms in make/FindFUSE.cmake like this:
```
# find lib
if (APPLE)
    SET(FUSE_NAMES libfuse.dylib libosxfuse.2.dylib libosxfuse_i64.2.dylib libosxfuse.dylib fuse)
else (APPLE)
    SET(FUSE_NAMES fuse)
endif (APPLE)
FIND_LIBRARY(FUSE_LIBRARIES
        NAMES ${FUSE_NAMES}
        PATHS /lib64 /lib /usr/lib64 /usr/lib /usr/local/lib64 /usr/local/lib
)
```

I also tried appending the library path:
```
dislocker2 % echo $LIBRARY_PATH
/usr/local/lib
```

as well as presetting it like with the cmake command:
`LIBRARY_PATH=/usr/local/lib:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib CPATH=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include make `

But the error remains, and I'm running out of ideas.
I'm not even sure where the check for losxfuse_i64 comes from. Perhaps this is not a dislocker problem, but maybe somebody has advice on how to find out which library exactly is expected here and where it should be found?
