### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by zeeshanali1993** [Aorimn/dislocker#219]
Getting a segmentation fault when trying to decrypt the external drive.

OS: Manjaro KDE Plasma (5.18.5)
Dislocker: 0.7.1-4

**Comment by zeeshanali1993** [comment]
Used dislocker-noruby (0.7.1-2) and it worked.

**Comment by Gallaher26Brel** [comment]
Hi, I'm facing the same issue on 0.7.1-4+b1
Currently using Debian 10.

HDD is a WD My Passport 25E2 (according to gparted)
using a GPT partition table

**Comment by d34thwalker** [comment]
I had the same issue with Arcolinux. I tried something out, with the following results.
crypted with win10 build 1909: segmentation fault
crypted with win10 build 2004: segmentation fault
crypted with win10 build 1703: everything works fine

**Comment by Aorimn** [comment]
Hi, a v0.7.3 tag has been pushed and should fix those issues.
