### ISSUE TITLE
Password with exclamation mark

### ISSUE THREAD

**Issue by oddclot** [Aorimn/dislocker#221]
Hi! I'm trying to decrypt my Bitlocker-encrypted hard drive on Ubuntu using the command:

`$ sudo dislocker /drive -u -- /destination`

But the thing is, my password contains an exclamation mark "!" at some point. Then the bash console thinks the string (let's say it's "string") after the ! is some kind of event and returns this:

`bash: !string: event not found`

Is there any workaround to solve this? Otherwise, any other option different than changing the password in a Windows PC?

Thanks!

**Comment by justephens** [comment]
You could try using your bitlocker recovery key, which can be found from your device menu in Microsoft's website. Use the `-p` option instead of `-u`, and type or paste your recovery key in to the prompt.

**Comment by Aorimn** [comment]
The exclamation mark is a special character for bash, you need to escape it when giving it to dislocker (or any other tool), e.g. (mind the simple quotes around the `-u` option):
```
# dislocker-fuse -V/dev/sda3 '-uAwesome123!' /mnt/dislocker
```
