### ISSUE TITLE
Decrypting using alternative recovery password

### ISSUE THREAD

**Issue by kohend** [Aorimn/dislocker#222]
I didn't want to have the base recovery password used on my Linux env, so I added a new recovery password via Windows (10 Pro), it didn't work with dislocker (it did with Windows).  
I wonder, is there an option I'm missing? Is the code hard-coded to use the first encrypted key?

**Comment by Aorimn** [comment]
It's a bug in dislocker indeed: the first key protector found is the one used, regardless if the key does decrypt the data.

**Comment by kohend** [comment]
So I'm thinking of fixing this in the code, and I think I'm close to finishing the basic code to do this, but I want to test it on something other than my main drive, any idea how to create a small test apart from using bitlocker to go?
