### ISSUE TITLE
[Bug?] Ubuntu 18.04: "du: cannot access '/media/ubuntu/windows/...': Input/output error"

### ISSUE THREAD

**Issue by AndrewL2018** [Aorimn/dislocker#224]
For some reason why, when I try to run the command, `du -sh /media/ubuntu/windows` (which is where I have the bitlocker encrypted drive mounted to; dislocker file is in its normal location) I keep getting these input/output errors. Am I doing something wrong, like when it comes to mounting the drive, or is getting sizes of files/directories inside the mounted drive not possible yet?

**Comment by Aorimn** [comment]
It seems there's a difference between `du` and `ls`:
```bash
# du -hs /media/dislocker/dislocker-file
0       /media/dislocker/dislocker-file
# ls -lh /media/dislocker/dislocker-file
-rw-rw-rw- 1 root root 142M Jan  1  1970 /media/dislocker/dislocker-file
```

This is on debian in a WSL2 environment. The file size isn't the same between the two calls.

I don't get the errors you're talking about, but there's definitely something weird here.

Using `strace` (first line for du, second for ls):
```
newfstatat(AT_FDCWD, "/media/dislocker/dislocker-file", {st_mode=S_IFREG|0666, st_size=148897792, ...}, AT_SYMLINK_NOFOLLOW) = 0

lstat("/media/dislocker/dislocker-file", {st_mode=S_IFREG|0666, st_size=148897792, ...}) = 0
```

Both times the `st_size` field is the same, so I'm not sure what's going on exactly.

----

On another note, is that an issue in your case? Are you using the size for something?

**Comment by AndrewL2018** [comment]
I was just wondering why it was having all these permissions issues, but I
found something else to help me out in the mean time.

>

**Comment by Aorimn** [comment]
Alright, closing this for now, thanks for reporting.
