### ISSUE TITLE
Could you please add a new tag?

### ISSUE THREAD

**Issue by haobinnan** [Aorimn/dislocker#227]
Could you please add a new tag, e.g.V0.7.2? Some Linux distributions are still using versions that have issues by default.

**Comment by Aorimn** [comment]
Unfortunately, I see multiple problems still, both of them when ruby is installed:
- doesn't [compile on OSX](https://travis-ci.org/github/Aorimn/dislocker/jobs/738910575)
- a [warning](https://travis-ci.org/github/Aorimn/dislocker/jobs/738910575#L5721) shows that recent changes haven't been fully ported

**Comment by Aorimn** [comment]
I've fixed the build, but [the warning](https://travis-ci.org/github/Aorimn/dislocker/jobs/741816203#L5781) (which should be an error in this case) is still here

**Comment by Aorimn** [comment]
I've also fixed the warning in the latest master.

@haobinnan : can you confirm this still works when trying to use a user password even though the Bitlocker volume hasn't been encrypted using one (e.g. encrypted with TPM only as you state in the commit) please?

**Comment by haobinnan** [comment]
Yes, I've tested. it does works.  So would it be possible to add a new tag, e.g. V0.7.2?

**Comment by haobinnan** [comment]
you can also have a check of this: https://github.com/Aorimn/dislocker/pull/228

**Comment by Aorimn** [comment]
@haobinnan the 0.7.2 is out of the oven, thanks for your hard work on this!
