### ISSUE TITLE
How to decrypt a volume if there is a space in a password?

### ISSUE THREAD

**Issue by adamryczkowski** [Aorimn/dislocker#230]
The man says I need to use like this (assuming existence of an empty `/media/bitlocker`):
```
sudo dislocker /dev/nvme0n1p3 -u<password> -- /media/bitlocker
```

How do I use a password that contains spaces? 

```
sudo dislocker /dev/nvme0n1p3 -u"Secret words" -- /media/bitlocker
```

does not seem to work.

**Comment by simon-perriard** [comment]
Have you tried to escape the space character like this: -uSecret\ words ?

**Comment by Aorimn** [comment]
I've never tested, but space should work like any other ascii character

**Comment by adamryczkowski** [comment]
Yes, spaces in password DO work on other computer. I still get the error but it is most probably caused by other thing. I have walked around the issue by decrypting the volume, so I am closing the issue for now.
