### ISSUE TITLE
fatal error: ruby.h: No such file or directory

### ISSUE THREAD

**Issue by nextgenthemes** [Aorimn/dislocker#231]
I have been using this for years, could always build it on Open SUSE Tubleweed

 But I ran into the following issues over time:

1. It stopped working, I think it was related to win10 update re-enabling fast boot so it was not really shutting down. May also be related to me having to rebuild it for new kernel.
2. The same thing or another, do not remember. I looked at the output and it was related to mounting the volume that had previously worked. It said something about exFAT for some reason (exFAT does actually not ship with open SUSE because its security sucks AFAIK). The only partition I mount is my win10 NTFS one. But I had `auto` as filesystem in fstab. After I switched it to `ntfs` it worked again, kind of.

Now it works only every 2nd time or something. Not sure if it worked when I had booting windows, or having it shutdown instead of reboot b4 or if its random but sometimes I have the volume at boot, other times I don't. 

Anyway I just wanted to build the latest version and this is happening.

```
cmake .
make          
[  0%] Built target dislocker-find
[  2%] Building C object src/CMakeFiles/dislocker.dir/dislocker.c.o
In file included from /home/u/dev/build/dislocker/include/dislocker/accesses/accesses.h:38,
                 from /home/u/dev/build/dislocker/src/dislocker.c:36:
/home/u/dev/build/dislocker/include/dislocker/ruby.h:40:10: fatal error: ruby.h: No such file or directory
   40 | #include <ruby.h>
      |          ^~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/dislocker.dir/build.make:82: src/CMakeFiles/dislocker.dir/dislocker.c.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:317: src/CMakeFiles/dislocker.dir/all] Fehler 2
make: *** [Makefile:149: all] Fehler 2

in ~/dev/build/dislocker/include/dislocker
ls
accesses  config.h       dislocker.h       encryption  metadata  return_values.h  ssl_bindings.h     xstd
common.h  config.priv.h  dislocker.priv.h  inouts      ntfs      ruby.h           ssl_bindings.h.in
```

Fedora with RPM packages is the closest to open SUSE to I installed all the deps listed for that, like I said I was able to build it b4 but I noticed that `rubypick` is no Open SUSE Tumbleweed package but `ruby-devel` is one and I have that installed. The error to me reads like it fails to read the file from within itself. The file is there for sure.

**Comment by Aorimn** [comment]
dislocker has a ruby.h file that wraps around the ruby.h from ruby-dev(el) package.

I have no clue why the ruby.h from your ruby-devel package isn't found though, it looks like an Open SUSE issue, or cmake configuration under Open SUSE though.

**Comment by nextgenthemes** [comment]
@Aorimn can you give me any hints how I may be able to find out what is happening? Files to look for  ...

The ruby packages seem to have no files, the commands list only docs. This seems weird to me.
```
rpm --query --list ruby         
/usr/share/doc/packages/ruby
/usr/share/doc/packages/ruby/README

rpm --query --list ruby-devel
/usr/share/doc/packages/ruby-devel
/usr/share/doc/packages/ruby-devel/README
```

This is the cmake output, there is a deprivation warning but it detects ruby correctly so I have no clue where to go from here.
```
cmake .
CMake Deprecation Warning at CMakeLists.txt:20 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found POLARSSL: /usr/include  
PolarSSL/mbedTLS version: 2.24.0
Ruby_FIND_VERSION=1.8.0
Ruby_FIND_VERSION_MAJOR=1
Ruby_FIND_VERSION_MINOR=8
Ruby_FIND_VERSION_PATCH=0
_Ruby_POSSIBLE_EXECUTABLE_NAMES=ruby;ruby2.7;ruby27;ruby2.6;ruby26;ruby2.5;ruby25;ruby2.4;ruby24;ruby2.3;ruby23;ruby2.2;ruby22;ruby2.1;ruby21;ruby2.0;ruby20;ruby1.9;ruby19;ruby1.8;ruby18
_Ruby_FIND_VIRTUALENV=STANDARD
_Ruby_FIND_VIRTUALENV doesn't match: STANDARD
-- --------FindRuby.cmake debug------------
-- _Ruby_POSSIBLE_EXECUTABLE_NAMES: ruby;ruby2.7;ruby27;ruby2.6;ruby26;ruby2.5;ruby25;ruby2.4;ruby24;ruby2.3;ruby23;ruby2.2;ruby22;ruby2.1;ruby21;ruby2.0;ruby20;ruby1.9;ruby19;ruby1.8;ruby18
-- _Ruby_POSSIBLE_LIB_NAMES: ruby;ruby-static;ruby2.7;ruby27;ruby-2.7;ruby-2.7.2
-- Ruby_ARCH_DIR: /usr/lib64/ruby/2.7.0/x86_64-linux-gnu
-- Ruby_HDR_DIR: /usr/include/ruby-2.7.0
-- Ruby_POSSIBLE_LIB_DIR: /usr/lib64
-- Found Ruby_VERSION: "2.7.2" , short: "2.7", nodot: "27"
-- _Ruby_REQUIRED_VARS: Ruby_EXECUTABLE;Ruby_INCLUDE_DIR;Ruby_LIBRARY;Ruby_CONFIG_INCLUDE_DIR
-- Ruby_EXECUTABLE: /usr/bin/ruby
-- Ruby_LIBRARY: /usr/lib64/libruby.so
-- Ruby_INCLUDE_DIR: /usr/include/ruby-2.7.0
-- Ruby_CONFIG_INCLUDE_DIR: /usr/include/ruby-2.7.0/x86_64-linux-gnu
-- --------------------
-- Found Ruby: /usr/bin/ruby (found suitable version "2.7.2", minimum required is "1.8.0") 
-- Found FUSE: /usr/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/u/dev/build/dislocker
```

**Comment by Aorimn** [comment]
Thanks for this output! What do you have in `/usr/include/ruby-2.7.0/x86_64-linux-gnu` (the value of `Ruby_CONFIG_INCLUDE_DIR`)?

Can you also provide the output of `make VERBOSE=1`?

**Comment by nextgenthemes** [comment]
Suddenly it works now. I did a system update and a reboot recently, that probably fixed it.

```
tree /usr/include/ruby-2.7.0/x86_64-linux-gnu
/usr/include/ruby-2.7.0/x86_64-linux-gnu
├── rb_mjit_min_header-2.7.2.h
└── ruby
    └── config.h
```
