### ISSUE TITLE
Unable to compile with Ruby 3.0 installed

### ISSUE THREAD

**Issue by oldpink** [Aorimn/dislocker#235]
I have run into a problem after upgrading Ruby from version 2.7.2 to Ruby version 3.0.
I ran into problems immediately with my already installed dislocker-find (version 0.7.3) after the upgrade, so I tried rebuilding Dislocker, running into multiple errors during the build process.
Downgrading to Ruby 2.7.2 resolved the issue, but I wanted to let the developers for Dislocker know about this.

Below is the output of the build attempt with Ruby 3.0 installed:

CMake Deprecation Warning at CMakeLists.txt:20 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The C compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
-- Found POLARSSL: /usr/include  
PolarSSL/mbedTLS version: 2.25.0
Ruby_FIND_VERSION=1.8.0
Ruby_FIND_VERSION_MAJOR=1
Ruby_FIND_VERSION_MINOR=8
Ruby_FIND_VERSION_PATCH=0
_Ruby_POSSIBLE_EXECUTABLE_NAMES=ruby;ruby2.7;ruby27;ruby2.6;ruby26;ruby2.5;ruby25;ruby2.4;ruby24;ruby2.3;ruby23;ruby2.2;ruby22;ruby2.1;ruby21;ruby2.0;ruby20;ruby1.9;ruby19;ruby1.8;ruby18
_Ruby_FIND_VIRTUALENV=STANDARD
_Ruby_FIND_VIRTUALENV doesn't match: STANDARD
-- --------FindRuby.cmake debug------------
-- _Ruby_POSSIBLE_EXECUTABLE_NAMES: ruby;ruby2.7;ruby27;ruby2.6;ruby26;ruby2.5;ruby25;ruby2.4;ruby24;ruby2.3;ruby23;ruby2.2;ruby22;ruby2.1;ruby21;ruby2.0;ruby20;ruby1.9;ruby19;ruby1.8;ruby18
-- _Ruby_POSSIBLE_LIB_NAMES: ruby;ruby-static;ruby3.0;ruby30;ruby-3.0;ruby-3.0.0
-- Ruby_ARCH_DIR: /usr/lib64/ruby/3.0.0/x86_64-linux
-- Ruby_HDR_DIR: /usr/include/ruby-3.0.0
-- Ruby_POSSIBLE_LIB_DIR: /usr/lib64
-- Found Ruby_VERSION: "3.0.0" , short: "3.0", nodot: "30"
-- _Ruby_REQUIRED_VARS: Ruby_EXECUTABLE;Ruby_INCLUDE_DIR;Ruby_LIBRARY;Ruby_CONFIG_INCLUDE_DIR
-- Ruby_EXECUTABLE: /usr/bin/ruby
-- Ruby_LIBRARY: /usr/lib64/libruby.so
-- Ruby_INCLUDE_DIR: /usr/include/ruby-3.0.0
-- Ruby_CONFIG_INCLUDE_DIR: /usr/include/ruby-3.0.0/x86_64-linux
-- --------------------
-- Found Ruby: /usr/bin/ruby (found suitable version "3.0.0", minimum required is "1.8.0") 
-- Found FUSE: /usr/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/SBo/dislocker-0.7.3/build
Scanning dependencies of target dislocker-find
/tmp/SBo/dislocker-0.7.3/man/linux/dislocker-find.1:	 49.5%
[  0%] Built target dislocker-find
Scanning dependencies of target dislocker
[  2%] Building C object src/CMakeFiles/dislocker.dir/xstd/xstdio.c.o
[ 10%] Building C object src/CMakeFiles/dislocker.dir/common.c.o
[ 10%] Building C object src/CMakeFiles/dislocker.dir/config.c.o
[ 10%] Building C object src/CMakeFiles/dislocker.dir/dislocker.c.o
[ 13%] Building C object src/CMakeFiles/dislocker.dir/xstd/xstdlib.c.o
[ 15%] Building C object src/CMakeFiles/dislocker.dir/metadata/datums.c.o
[ 18%] Building C object src/CMakeFiles/dislocker.dir/metadata/metadata.c.o
[ 21%] Building C object src/CMakeFiles/dislocker.dir/metadata/vmk.c.o
In file included from /usr/include/ruby-3.0.0/ruby/internal/stdbool.h:40,
                 from /usr/include/ruby-3.0.0/ruby/backward/2/bool.h:23,
                 from /usr/include/ruby-3.0.0/ruby/defines.h:74,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:23,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from /tmp/SBo/dislocker-0.7.3/include/dislocker/ruby.h:40,
                 from /tmp/SBo/dislocker-0.7.3/include/dislocker/common.h:83,
                 from /tmp/SBo/dislocker-0.7.3/src/config.c:28:
/tmp/SBo/dislocker-0.7.3/src/config.c: In function ‘setclearkey’:
/tmp/SBo/dislocker-0.7.3/src/config.c:59:6: error: expected identifier or ‘(’ before numeric constant
   59 |  int true = TRUE;
      |      ^~~~
/tmp/SBo/dislocker-0.7.3/src/config.c:60:45: error: lvalue required as unary ‘&’ operand
   60 |  dis_setopt(dis_ctx, DIS_OPT_USE_CLEAR_KEY, &true);
      |                                             ^
In file included from /usr/include/ruby-3.0.0/ruby/internal/stdbool.h:40,
                 from /usr/include/ruby-3.0.0/ruby/backward/2/bool.h:23,
                 from /usr/include/ruby-3.0.0/ruby/defines.h:74,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:23,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from /tmp/SBo/dislocker-0.7.3/include/dislocker/ruby.h:40,
                 from /tmp/SBo/dislocker-0.7.3/include/dislocker/common.h:83,
                 from /tmp/SBo/dislocker-0.7.3/src/config.c:28:
/tmp/SBo/dislocker-0.7.3/src/config.c: In function ‘setbekfile’:
/tmp/SBo/dislocker-0.7.3/src/config.c:64:6: error: expected identifier or ‘(’ before numeric constant
   64 |  int true = TRUE;
      |      ^~~~
/tmp/SBo/dislocker-0.7.3/src/config.c:65:44: error: lvalue required as unary ‘&’ operand
   65 |  dis_setopt(dis_ctx, DIS_OPT_USE_BEK_FILE, &true);
      |                                            ^
In file included from /usr/include/ruby-3.0.0/ruby/internal/stdbool.h:40,
                 from /usr/include/ruby-3.0.0/ruby/backward/2/bool.h:23,
                 from /usr/include/ruby-3.0.0/ruby/defines.h:74,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:23,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from /tmp/SBo/dislocker-0.7.3/include/dislocker/ruby.h:40,
                 from /tmp/SBo/dislocker-0.7.3/include/dislocker/common.h:83,
                 from /tmp/SBo/dislocker-0.7.3/src/config.c:28:
/tmp/SBo/dislocker-0.7.3/src/config.c: In function ‘setfvek’:
/tmp/SBo/dislocker-0.7.3/src/config.c:79:6: error: expected identifier or ‘(’ before numeric constant
   79 |  int true = TRUE;
      |      ^~~~
/tmp/SBo/dislocker-0.7.3/src/config.c:80:45: error: lvalue required as unary ‘&’ operand
   80 |  dis_setopt(dis_ctx, DIS_OPT_USE_FVEK_FILE, &true);
      |                                             ^
In file included from /usr/include/ruby-3.0.0/ruby/internal/stdbool.h:40,
                 from /usr/include/ruby-3.0.0/ruby/backward/2/bool.h:23,
                 from /usr/include/ruby-3.0.0/ruby/defines.h:74,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:23,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from /tmp/SBo/dislocker-0.7.3/include/dislocker/ruby.h:40,
                 from /tmp/SBo/dislocker-0.7.3/include/dislocker/common.h:83,
                 from /tmp/SBo/dislocker-0.7.3/src/config.c:28:
/tmp/SBo/dislocker-0.7.3/src/config.c: In function ‘setvmk’:
/tmp/SBo/dislocker-0.7.3/src/config.c:85:6: error: expected identifier or ‘(’ before numeric constant
   85 |  int true = TRUE;
      |      ^~~~
/tmp/SBo/dislocker-0.7.3/src/config.c:86:44: error: lvalue required as unary ‘&’ operand
   86 |  dis_setopt(dis_ctx, DIS_OPT_USE_VMK_FILE, &true);
      |                                            ^
In file included from /usr/include/ruby-3.0.0/ruby/internal/stdbool.h:40,
                 from /usr/include/ruby-3.0.0/ruby/backward/2/bool.h:23,
                 from /usr/include/ruby-3.0.0/ruby/defines.h:74,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:23,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from /tmp/SBo/dislocker-0.7.3/include/dislocker/ruby.h:40,
                 from /tmp/SBo/dislocker-0.7.3/include/dislocker/common.h:83,
                 from /tmp/SBo/dislocker-0.7.3/src/config.c:28:
/tmp/SBo/dislocker-0.7.3/src/config.c: In function ‘setrecoverypwd’:
/tmp/SBo/dislocker-0.7.3/src/config.c:100:6: error: expected identifier or ‘(’ before numeric constant
  100 |  int true = TRUE;
      |      ^~~~
/tmp/SBo/dislocker-0.7.3/src/config.c:101:53: error: lvalue required as unary ‘&’ operand
  101 |  dis_setopt(dis_ctx, DIS_OPT_USE_RECOVERY_PASSWORD, &true);
      |                                                     ^
In file included from /usr/include/ruby-3.0.0/ruby/internal/stdbool.h:40,
                 from /usr/include/ruby-3.0.0/ruby/backward/2/bool.h:23,
                 from /usr/include/ruby-3.0.0/ruby/defines.h:74,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:23,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from /tmp/SBo/dislocker-0.7.3/include/dislocker/ruby.h:40,
                 from /tmp/SBo/dislocker-0.7.3/include/dislocker/common.h:83,
                 from /tmp/SBo/dislocker-0.7.3/src/config.c:28:
/tmp/SBo/dislocker-0.7.3/src/config.c: In function ‘setro’:
/tmp/SBo/dislocker-0.7.3/src/config.c:114:6: error: expected identifier or ‘(’ before numeric constant
  114 |  int true = TRUE;
      |      ^~~~
/tmp/SBo/dislocker-0.7.3/src/config.c:115:41: error: lvalue required as unary ‘&’ operand
  115 |  dis_setopt(dis_ctx, DIS_OPT_READ_ONLY, &true);
      |                                         ^
In file included from /usr/include/ruby-3.0.0/ruby/internal/stdbool.h:40,
                 from /usr/include/ruby-3.0.0/ruby/backward/2/bool.h:23,
                 from /usr/include/ruby-3.0.0/ruby/defines.h:74,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:23,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from /tmp/SBo/dislocker-0.7.3/include/dislocker/ruby.h:40,
                 from /tmp/SBo/dislocker-0.7.3/include/dislocker/common.h:83,
                 from /tmp/SBo/dislocker-0.7.3/src/config.c:28:
/tmp/SBo/dislocker-0.7.3/src/config.c: In function ‘setstateok’:
/tmp/SBo/dislocker-0.7.3/src/config.c:120:6: error: expected identifier or ‘(’ before numeric constant
  120 |  int true = TRUE;
      |      ^~~~
/tmp/SBo/dislocker-0.7.3/src/config.c:121:55: error: lvalue required as unary ‘&’ operand
  121 |  dis_setopt(dis_ctx, DIS_OPT_DONT_CHECK_VOLUME_STATE, &true);
      |                                                       ^
In file included from /usr/include/ruby-3.0.0/ruby/internal/stdbool.h:40,
                 from /usr/include/ruby-3.0.0/ruby/backward/2/bool.h:23,
                 from /usr/include/ruby-3.0.0/ruby/defines.h:74,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:23,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from /tmp/SBo/dislocker-0.7.3/include/dislocker/ruby.h:40,
                 from /tmp/SBo/dislocker-0.7.3/include/dislocker/common.h:83,
                 from /tmp/SBo/dislocker-0.7.3/src/config.c:28:
/tmp/SBo/dislocker-0.7.3/src/config.c: In function ‘setuserpassword’:
/tmp/SBo/dislocker-0.7.3/src/config.c:125:6: error: expected identifier or ‘(’ before numeric constant
  125 |  int true = TRUE;
      |      ^~~~
/tmp/SBo/dislocker-0.7.3/src/config.c:126:49: error: lvalue required as unary ‘&’ operand
  126 |  dis_setopt(dis_ctx, DIS_OPT_USE_USER_PASSWORD, &true);
      |                                                 ^
In file included from /usr/include/ruby-3.0.0/ruby/internal/stdbool.h:40,
                 from /usr/include/ruby-3.0.0/ruby/backward/2/bool.h:23,
                 from /usr/include/ruby-3.0.0/ruby/defines.h:74,
                 from /usr/include/ruby-3.0.0/ruby/ruby.h:23,
                 from /usr/include/ruby-3.0.0/ruby.h:38,
                 from /tmp/SBo/dislocker-0.7.3/include/dislocker/ruby.h:40,
                 from /tmp/SBo/dislocker-0.7.3/include/dislocker/common.h:83,
                 from /tmp/SBo/dislocker-0.7.3/src/config.c:28:
/tmp/SBo/dislocker-0.7.3/src/config.c: In function ‘dis_getopts’:
/tmp/SBo/dislocker-0.7.3/src/config.c:269:6: error: expected identifier or ‘(’ before numeric constant
  269 |  int true = TRUE;
      |      ^~~~
/tmp/SBo/dislocker-0.7.3/src/config.c:288:48: error: lvalue required as unary ‘&’ operand
  288 |     dis_setopt(dis_ctx, DIS_OPT_USE_CLEAR_KEY, &true);
      |                                                ^
/tmp/SBo/dislocker-0.7.3/src/config.c:293:47: error: lvalue required as unary ‘&’ operand
  293 |     dis_setopt(dis_ctx, DIS_OPT_USE_BEK_FILE, &true);
      |                                               ^
/tmp/SBo/dislocker-0.7.3/src/config.c:315:48: error: lvalue required as unary ‘&’ operand
  315 |     dis_setopt(dis_ctx, DIS_OPT_USE_FVEK_FILE, &true);
      |                                                ^
/tmp/SBo/dislocker-0.7.3/src/config.c:321:47: error: lvalue required as unary ‘&’ operand
  321 |     dis_setopt(dis_ctx, DIS_OPT_USE_VMK_FILE, &true);
      |                                               ^
/tmp/SBo/dislocker-0.7.3/src/config.c:343:56: error: lvalue required as unary ‘&’ operand
  343 |     dis_setopt(dis_ctx, DIS_OPT_USE_RECOVERY_PASSWORD, &true);
      |                                                        ^
/tmp/SBo/dislocker-0.7.3/src/config.c:356:44: error: lvalue required as unary ‘&’ operand
  356 |     dis_setopt(dis_ctx, DIS_OPT_READ_ONLY, &true);
      |                                            ^
/tmp/SBo/dislocker-0.7.3/src/config.c:361:58: error: lvalue required as unary ‘&’ operand
  361 |     dis_setopt(dis_ctx, DIS_OPT_DONT_CHECK_VOLUME_STATE, &true);
      |                                                          ^
/tmp/SBo/dislocker-0.7.3/src/config.c:366:52: error: lvalue required as unary ‘&’ operand
  366 |     dis_setopt(dis_ctx, DIS_OPT_USE_USER_PASSWORD, &true);
      |                                                    ^
[ 23%] Building C object src/CMakeFiles/dislocker.dir/metadata/fvek.c.o
make[2]: *** [src/CMakeFiles/dislocker.dir/build.make:108: src/CMakeFiles/dislocker.dir/config.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:317: src/CMakeFiles/dislocker.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

**Comment by Aorimn** [comment]
Thanks for the bug report!

This issue is... weird 🤔 
It's like compiling with ruby 3.0 prepend line numbers and a pipe to some of dislocker's .c file. I'll have a look at it when I have some time.

**Comment by oldpink** [comment]
Thank you for the response.
Also, thanks massively for Dislocker!

**Comment by oldpink** [comment]
FYI, I was able to locate a patch that now allows the program to fully compile without any problems with Ruby 3.0.
The patch is below, and I will close this issue upon request, but I will leave it open at least long enough to put up the patch here for others to comment on for a possible direct incorporation directly into the next release.
I found the patch within the source archive here: https://download-ib01.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/source/tree/Packages/d/dislocker-0.7.3-2.fc34.src.rpm


--- dislocker-0.7.3/src/config.c.duplicate	2020-11-18 05:29:35.000000000 +0900
+++ dislocker-0.7.3/src/config.c	2021-01-07 16:03:36.817405937 +0900
@@ -56,13 +56,13 @@ static void hide_opt(char* opt)
 static void setclearkey(dis_context_t dis_ctx, char* optarg)
 {
 	(void) optarg;
-	int true = TRUE;
-	dis_setopt(dis_ctx, DIS_OPT_USE_CLEAR_KEY, &true);
+	int trueval = TRUE;
+	dis_setopt(dis_ctx, DIS_OPT_USE_CLEAR_KEY, &trueval);
 }
 static void setbekfile(dis_context_t dis_ctx, char* optarg)
 {
-	int true = TRUE;
-	dis_setopt(dis_ctx, DIS_OPT_USE_BEK_FILE, &true);
+	int trueval = TRUE;
+	dis_setopt(dis_ctx, DIS_OPT_USE_BEK_FILE, &trueval);
 	dis_setopt(dis_ctx, DIS_OPT_SET_BEK_FILE_PATH, optarg);
 }
 static void setforceblock(dis_context_t dis_ctx, char* optarg)
@@ -76,14 +76,14 @@ static void setforceblock(dis_context_t
 }
 static void setfvek(dis_context_t dis_ctx, char* optarg)
 {
-	int true = TRUE;
-	dis_setopt(dis_ctx, DIS_OPT_USE_FVEK_FILE, &true);
+	int trueval = TRUE;
+	dis_setopt(dis_ctx, DIS_OPT_USE_FVEK_FILE, &trueval);
 	dis_setopt(dis_ctx, DIS_OPT_SET_FVEK_FILE_PATH, optarg);
 }
 static void setvmk(dis_context_t dis_ctx, char* optarg)
 {
-	int true = TRUE;
-	dis_setopt(dis_ctx, DIS_OPT_USE_VMK_FILE, &true);
+	int trueval = TRUE;
+	dis_setopt(dis_ctx, DIS_OPT_USE_VMK_FILE, &trueval);
 	dis_setopt(dis_ctx, DIS_OPT_SET_VMK_FILE_PATH, optarg);
 }
 static void setlogfile(dis_context_t dis_ctx, char* optarg)
@@ -97,8 +97,8 @@ static void setoffset(dis_context_t dis_
 }
 static void setrecoverypwd(dis_context_t dis_ctx, char* optarg)
 {
-	int true = TRUE;
-	dis_setopt(dis_ctx, DIS_OPT_USE_RECOVERY_PASSWORD, &true);
+	int trueval = TRUE;
+	dis_setopt(dis_ctx, DIS_OPT_USE_RECOVERY_PASSWORD, &trueval);
 	dis_setopt(dis_ctx, DIS_OPT_SET_RECOVERY_PASSWORD, optarg);
 	hide_opt(optarg);
 }
@@ -111,19 +111,19 @@ static void setquiet(dis_context_t dis_c
 static void setro(dis_context_t dis_ctx, char* optarg)
 {
 	(void) optarg;
-	int true = TRUE;
-	dis_setopt(dis_ctx, DIS_OPT_READ_ONLY, &true);
+	int trueval = TRUE;
+	dis_setopt(dis_ctx, DIS_OPT_READ_ONLY, &trueval);
 }
 static void setstateok(dis_context_t dis_ctx, char* optarg)
 {
 	(void) optarg;
-	int true = TRUE;
-	dis_setopt(dis_ctx, DIS_OPT_DONT_CHECK_VOLUME_STATE, &true);
+	int trueval = TRUE;
+	dis_setopt(dis_ctx, DIS_OPT_DONT_CHECK_VOLUME_STATE, &trueval);
 }
 static void setuserpassword(dis_context_t dis_ctx, char* optarg)
 {
-	int true = TRUE;
-	dis_setopt(dis_ctx, DIS_OPT_USE_USER_PASSWORD, &true);
+	int trueval = TRUE;
+	dis_setopt(dis_ctx, DIS_OPT_USE_USER_PASSWORD, &trueval);
 	dis_setopt(dis_ctx, DIS_OPT_SET_USER_PASSWORD, optarg);
 	hide_opt(optarg);
 }
@@ -266,7 +266,7 @@ int dis_getopts(dis_context_t dis_ctx, i
 		return -1;
 
 	dis_config_t* cfg = &dis_ctx->cfg;
-	int true = TRUE;
+	int trueval = TRUE;
 
 
 	long_opts = malloc(nb_options * sizeof(struct option));
@@ -285,12 +285,12 @@ int dis_getopts(dis_context_t dis_ctx, i
 		{
 			case 'c':
 			{
-				dis_setopt(dis_ctx, DIS_OPT_USE_CLEAR_KEY, &true);
+				dis_setopt(dis_ctx, DIS_OPT_USE_CLEAR_KEY, &trueval);
 				break;
 			}
 			case 'f':
 			{
-				dis_setopt(dis_ctx, DIS_OPT_USE_BEK_FILE, &true);
+				dis_setopt(dis_ctx, DIS_OPT_USE_BEK_FILE, &trueval);
 				dis_setopt(dis_ctx, DIS_OPT_SET_BEK_FILE_PATH, optarg);
 				break;
 			}
@@ -312,13 +312,13 @@ int dis_getopts(dis_context_t dis_ctx, i
 			}
 			case 'k':
 			{
-				dis_setopt(dis_ctx, DIS_OPT_USE_FVEK_FILE, &true);
+				dis_setopt(dis_ctx, DIS_OPT_USE_FVEK_FILE, &trueval);
 				dis_setopt(dis_ctx, DIS_OPT_SET_FVEK_FILE_PATH, optarg);
 				break;
 			}
 			case 'K':
 			{
-				dis_setopt(dis_ctx, DIS_OPT_USE_VMK_FILE, &true);
+				dis_setopt(dis_ctx, DIS_OPT_USE_VMK_FILE, &trueval);
 				dis_setopt(dis_ctx, DIS_OPT_SET_VMK_FILE_PATH, optarg);
 				break;
 			}
@@ -340,7 +340,7 @@ int dis_getopts(dis_context_t dis_ctx, i
 			}
 			case 'p':
 			{
-				dis_setopt(dis_ctx, DIS_OPT_USE_RECOVERY_PASSWORD, &true);
+				dis_setopt(dis_ctx, DIS_OPT_USE_RECOVERY_PASSWORD, &trueval);
 				dis_setopt(dis_ctx, DIS_OPT_SET_RECOVERY_PASSWORD, optarg);
 				hide_opt(optarg);
 				break;
@@ -353,17 +353,17 @@ int dis_getopts(dis_context_t dis_ctx, i
 			}
 			case 'r':
 			{
-				dis_setopt(dis_ctx, DIS_OPT_READ_ONLY, &true);
+				dis_setopt(dis_ctx, DIS_OPT_READ_ONLY, &trueval);
 				break;
 			}
 			case 's':
 			{
-				dis_setopt(dis_ctx, DIS_OPT_DONT_CHECK_VOLUME_STATE, &true);
+				dis_setopt(dis_ctx, DIS_OPT_DONT_CHECK_VOLUME_STATE, &trueval);
 				break;
 			}
 			case 'u':
 			{
-				dis_setopt(dis_ctx, DIS_OPT_USE_USER_PASSWORD, &true);
+				dis_setopt(dis_ctx, DIS_OPT_USE_USER_PASSWORD, &trueval);
 				dis_setopt(dis_ctx, DIS_OPT_SET_USER_PASSWORD, optarg);
 				hide_opt(optarg);
 				break;

**Comment by mtasaka** [comment]
see: https://github.com/Aorimn/dislocker/pull/236

**Comment by oldpink** [comment]
I'll close this one for now, since I found a solution via the above patch.
I trust that the developers will incorporate a variation of the patch in the next release.
