### ISSUE TITLE
Will there be an android version of dislocker?

### ISSUE THREAD

**Issue by Jailman** [Aorimn/dislocker#259]
Well, hello, I'm using bitlocker on multi-platforms, especially on mobile devices, could it be possible to make an android version?

**Comment by superbonaci** [comment]
I think it would require a kernel module incorporated by each manufacturer, so it has hardware accelerated encryption and decryption (on-the-fly), which is not going to happen in the near future. I would look forward to smartphones with GNU/Linux in the future, don't put your energy into Android or Apple devices. The target is media consumption.

Take a look at [PinePhone](https://www.pine64.org/pinephone/).

**Comment by superbonaci** [comment]
Be kind to close the issue, because dislocker is not responsible for this.

**Comment by Aorimn** [comment]
I wouldn't know how to start this, but will welcome any PR adding the support for Android (without any guarantee that future dislocker versions will be able to run on Android).

**Comment by superbonaci** [comment]
Probably you will need root access to really use it for storage purposes.
