### ISSUE TITLE
FUSE version

### ISSUE THREAD

**Issue by Phaiax** [Aorimn/dislocker#26]
Hey

It's cool that you are continuing working on this lib. I found that the 0.4.1 version is a little bit slow (I only get a write speed of 5 MB/s), so I wanted to test the develop branch.

INSTALL.txt says, that I would need FUSE 2.6
But my fedora, as well as Ubuntu 10.04 comes with FUSE 2.9

Is this an is outdated information?

Thank you,
Phaiax

**Comment by Phaiax** [comment]
okay, I just tried it and it seems to work.
But write speed is still low (after some buffer of maybe 1GB has been filled up)

Would it be hard to improve speed?

**Comment by Aorimn** [comment]
Indeed, the INSTALL file is misleading, so I've added "at least", it should be better.

I'm not sure where the bottleneck is, if you have an idea, I'm okay to work on it.
