### ISSUE TITLE
Update version on Apt

### ISSUE THREAD

**Issue by mkierzenka** [Aorimn/dislocker#262]
Hi, I'm looking to use this project on an embedded system running Ubuntu 18.04. However, I noticed that _the latest version available in the apt package manager for that distro version is 0.7.1_ which unfortunately does not have the ability to read user passwords from pipes (a 0.7.2 feature). I require this feature for the script I am writing to automount decrypted sd cards.

I built the 0.7.2 code manually and it seems to run fine, but it is tricky to deploy pre-built packages in my setup and building on the target system is not an option. **Is there any chance you could update the version available for Ubuntu 18.04 in Apt?**

**Comment by Aorimn** [comment]
Hi, unfortunately, I'm not maintaining downstream packages of dislocker. For ubuntu, you should maybe try their forum? I don't know what's their politic for such issues
