### ISSUE TITLE
contents of fusemount dir not readable

### ISSUE THREAD

**Issue by binarynoise** [Aorimn/dislocker#267]
When I use the command `sudo dislocker -v -V /dev/sdb1 -u -- /mnt/b`, enter the user password, and then do `ll` I get:
```
ls: Zugriff auf 'b' nicht möglich: Access Denied
insgesamt 12
drwxr-xr-x  4 root root 4096 Sep 24 20:42 ./
drwxr-xr-x 19 root root 4096 Jun 18 14:32 ../
d?????????  ? ?    ?       ?            ? b/
drwxr-xr-x  2 root root 4096 Sep 24 20:42 bm/
```

If I run `ll` as root, it shows 
```
dr-xr-xr-x  2 root root    0 Jan  1  1970 b
```

Which is very annoying because you think, dislocker srewed up.
Please make that dir ls-able by normal users.

**Comment by Aorimn** [comment]
If it works for root, then the issue doesn't look to be dislocker-related. You should try to have a look at fuse's mount options, such as `allow_other`.

**Comment by binarynoise** [comment]
How do I pass fuse options to dislocker?
I think you may have misunderstood or I haven't been clear enough: It's the dir that dislocker uses to mount the dislocker-file that is not readable. The fuse mount dir is readable without problems.
So why can't I read the contents of the dislocker-file-dir after mounting it using dislocker, when before r/w-access was no problem?
