### ISSUE TITLE
About a more detailed definition of verify structure

### ISSUE THREAD

**Issue by haobinnan** [Aorimn/dislocker#269]
May I know if you have more detailed information about the _bitlocker_validations structure? I have noted that in addition to the definition of 8 bytes in the structure, there are also some verifications in the following dozens of bytes. If the data in metadata is modified, it will not work to recalculate crc32 only, as the next dozens of bytes should also be recalculated.

@Aorimn

**Comment by Aorimn** [comment]
Everything I have is in the code, which looks to be "documented" in the [structure's comments](https://github.com/Aorimn/dislocker/blob/ad87d029025e2ee69c2d18edbcc483603076e0f7/include/dislocker/metadata/metadata.priv.h#L192-L200). But this describes the static state of the structure when Windows is off, I have no idea of when this is actually used.

**Comment by haobinnan** [comment]
thanks
