### ISSUE TITLE
Can't mount loop device

### ISSUE THREAD

**Issue by QkiZMR** [Aorimn/dislocker#27]
I was successfully compile dislocker on Ubuntu. After
sudo dislocker -r -u -v -V /dev/sdb1 /mnt/
command I want to mount dislocker-file but if ran command
mount /mnt/dislocker-file /media/virtual/ -o loop
I get 
fuse: mount failed: Access Denied
I'm calling this commands from root.

**Comment by Aorimn** [comment]
You probably need to run `sudo su -`, then `dislocker -r -u -v -V /dev/sdb1 /mnt/`, and finally the mount command `mount /mnt/dislocker-file /media/virtual/ -o loop`.

FUSE has weird ways of dealing with privileges. If you're willing to stick with sudo for the first command, something like that might work: `sudo dislocker -r -u -v -V /dev/sdb1 -- /mnt/ -o allow_root`

**Comment by QkiZMR** [comment]
Same message.

**Comment by Aorimn** [comment]
It's normal that the normal user can't see the file.
Could you be more specific on the commands you run and from which user (normal or root) please?

Also, which version of Ubuntu are you using?

**Comment by QkiZMR** [comment]
Ubuntu 14.10 64bit
Commands:
$ sudo su -
# dislocker -r -u -v -V /dev/sdb1 -- /mnt/
Enter the user password:
# mount /mnt/dislocker-file /media/virtual/ -o loop
fuse: mount failed: Access Denied

**Comment by Aorimn** [comment]
If you're using the `-r` option from dislocker, you'll need to pass `-o ro` to mount, it seems that mount doesn't failover to this option by default here.
You're not required to pass `-o loop` though, it seems this option is implicit, but if you want to, then the mount command would become `mount /mnt/dislocker-file /media/virtual/ -o loop,ro`

**Comment by QkiZMR** [comment]
It works! :) Thank's. ro option do the job.

**Comment by Aorimn** [comment]
Great :-)
