### ISSUE TITLE
Not able to unlock partition, dislocker is messing up mount directory permissions.

### ISSUE THREAD

**Issue by mariot8** [Aorimn/dislocker#271]
`dislocker by Romain Coltel, v0.7.1 (compiled for Linux/x86_64)`
Mounting with:`sudo dislocker -v -V /dev/sda1 -u -- /media/sandisk_loop/`
Is causing messed up permisions:
`ls -la /media/sandisk_loop`
`d????????? ? ?       ?          ?            ? sandisk_loop`

**Comment by Aorimn** [comment]
This is most probably due to fuse not allowing other users to see the file.
Please try to add `-o allow_other` at the end of the dislocker command. Have a look at `man 8 fuse` for further info
