### ISSUE TITLE
Regarding patent issue

### ISSUE THREAD

**Issue by ChungkiWoo** [Aorimn/dislocker#272]
Hello. I am Chungki Woo from South Korea.

I have one question regarding dislocker.
Is there any patent issue(From Microsoft for example) to use dislocker in some commercial product?

Thank you in advance.

**Comment by Aorimn** [comment]
Hi @ChungkiWoo , I don't see why MS would have any patent on dislocker, but I'm no lawyer.

For dislocker itself though, its license is given on this file: https://github.com/Aorimn/dislocker/blob/master/LICENSE.txt
