### ISSUE TITLE
How i can get VMK or recovery key?

### ISSUE THREAD

**Issue by SalkovAA** [Aorimn/dislocker#273]
Hello!  I get Bitlocker recovery key with "manage-bde -protectors C: -get". How i can get Bitlocker recovery key or VMK, after i unlock volume with FVEK?

**Comment by DanielKirshner** [comment]
You can't get the recovery/VMK after decrypting the disk. 
The decryption "removes" the bitlocker encryption keys and protectors, including the recovery key.

**Comment by SalkovAA** [comment]
> You can't get the recovery/VMK after decrypting the disk.
> The decryption "removes" the bitlocker encryption keys and protectors, including the recovery key.

Yes, if I decrypt the bitlocker volume it will clear the protector. But if I unlock volume with dislocker-fuse, then the bitlocker protector will be saved

**Comment by DanielKirshner** [comment]
No. 
That's exactly the same thing as decrypting from the windows GUI.

**Comment by DanielKirshner** [comment]
@SalkovAA 
No.
That's exactly the same thing as decrypting from the windows GUI.

**Comment by Aorimn** [comment]
Hi, there's no functionality in dislocker to provide you the recovery key or the VMK.

It may be possible thanks to the encrypted metadata, but I'm not sure and as said above it's not implemented
