### ISSUE TITLE
Password/Recovery Key in command line

### ISSUE THREAD

**Issue by QkiZMR** [Aorimn/dislocker#30]
I'm working on a script to quick mount encrypted Windows volume. I want to give password in a command line, as a parameter. Is it possible?

**Comment by Aorimn** [comment]
You can give the user password, the recovery password or the recovery key through command line, respectively:
`-uUSERPASSWORD`
`-pRECOVERYPASSWORD`
`-fRECOVERYKEYFILE`

Note that you have to stick the option letter (`u` and `p`) to the passwords (it's a getopt limitation).

**Comment by QkiZMR** [comment]
Thanks. Its works.
