### ISSUE TITLE
Pull request 280 breaks most Linux builds

### ISSUE THREAD

**Issue by Mikero123** [Aorimn/dislocker#304]
It appears that pull request 280 apparently updates the code to use mbedtls v3.x  most linux systems (ubuntu and rocky are the ones I have tested) are still on 2.9.9

Here is the build error I am seeing:
-- Detecting C compile features - done
-- Found POLARSSL: /usr/include  
a.c:1:10: fatal error: mbedtls/build_info.h: No such file or directory
    1 | #include <mbedtls/build_info.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
PolarSSL/mbedTLS version: 
CMake Error at cmake/FindPolarSSL.cmake:87 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  src/CMakeLists.txt:119 (find_package)

Here is the migration note reference:

https://review.trustedfirmware.org/plugins/gitiles/mirror/mbed-tls/+/bd3bfbf5c2a87a19303d1e1c55f01b03084f32d8/docs/3.0-migration-guide.md

**Comment by Aorimn** [comment]
PR has been revert, we'll need another fix that doesn't break Linux builds. Thanks for the report
