### ISSUE TITLE
Incompatible with latest libpolarssl (now called libmbedtls)

### ISSUE THREAD

**Issue by tompccs** [Aorimn/dislocker#33]
No longer compiles or runs after latest update to libpolarssl. I now get the following compilation error:

/usr/bin/ld: /usr/local/lib/libpolarssl.a(aes.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC

...and the following error when trying to run the already-compiled binary:

dislocker: error while loading shared libraries: libpolarssl.so.6: cannot open shared object file: No such file or directory

**Comment by Aorimn** [comment]
A fix is on its way on the cmake branch. The fix should find which package is available, therefore which package to use.

**Comment by fgranda** [comment]
Just came up with this when I tried to use dislocker for a forensic job. Any update on what package or ssl library to use instead?

**Comment by Aorimn** [comment]
The newly merged cmake branch in the develop one make it possible to link against polarssl or mbedTLS.
Note that the install process is a little bit changed due to the use of cmake.

**Comment by fgranda** [comment]
Awesome thanks. I'm going to check it out later today or this week and test out the compile. I'll let you know how it goes..

**Comment by Aorimn** [comment]
Any news @fgranda ?
