### ISSUE TITLE
./config.h:87: error: expected specifier-qualifier-list before 'off_t'

### ISSUE THREAD

**Issue by robert-scheck** [Aorimn/dislocker#35]
Building dislocker 0.4.1 on RHEL/CentOS 5 fails as follows:

    In file included from ./dislocker.h:28,
                     from accesses/accesses.h:27,
                     from dislocker.c:28:
    ./config.h:87: error: expected specifier-qualifier-list before 'off_t'

and

    dislocker.c: In function 'dis_initialize':
    dislocker.c:112: error: 'dis_config_t' has no member named 'is_ro'
    dislocker.c:144: error: 'dis_config_t' has no member named 'offset'
    dislocker.c:344: error: 'dis_config_t' has no member named 'dont_check_state'

**Comment by robert-scheck** [comment]
The issue can be solved by adding

    #include <sys/types.h>

in src/config.h. Can this please happen in an appropriate way at upstream?

**Comment by Aorimn** [comment]
Hi, thanks for reporting this. It should be fixed in the develop branch, feel free to reopen the issue if it isn't.
