### ISSUE TITLE
metadata/fvek.c:153:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]

### ISSUE THREAD

**Issue by robert-scheck** [Aorimn/dislocker#36]
Building dislocker 0.4.1 on Fedora 22 leads to this:

    metadata/fvek.c: In function 'build_fvek_from_file':
    metadata/fvek.c:153:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
      datum_key->algo = *(cipher_t*)enc_method;
      ^
    cc1: all warnings being treated as errors

**Comment by Aorimn** [comment]
These strict-aliasing problems have been fixed in the develop branch. I'll make a new version in a few weeks if it's ok with you to wait for this release.
