### ISSUE TITLE
Error while executing (KALI x64)

### ISSUE THREAD

**Issue by shargon** [Aorimn/dislocker#41]
error while loading shared libraries: libdislocker.so.0: cannot open shared object file: No such file or directory

**Comment by bxkatze** [comment]
I have Dislocker working on Kali x64 after nominal troubles with libdislocker.so.0, I should have documented the process better but this should be it:

After running 'make install' in the 'src' directory of the uncompressed Dislocker directory, run this while in the same dir: 'install -pm755 libdislocker.so.0.4.1  /usr/lib'

For some reason, when Dislocker is installed with 'make install,' the needed libdislocker.so.0 is not installed in /usr/lib as it should be.. but works after manually placing it there.

I hope I have taken the correct measure from my bash history so I am not posing bad info!
