### ISSUE TITLE
make dislocker fail on 10.9.5

### ISSUE THREAD

**Issue by drento** [Aorimn/dislocker#48]
clang -Wall -Werror -Wextra -Qunused-arguments -DPROGNAME=\"dislocker\" -DVERSION=\"0.4.1\" -D_FILE_OFFSET_BITS=64 -DAUTHOR="\"Romain Coltel\"" -D__OS=\"Darwin\" -D__ARCH=\"x86_64\" -D__ARCH_X86_64 -D__DARWIN -I. -I/usr/local/include -fstack-protector -fPIC -D_FORTIFY_SOURCE=2 -O1 -c -o dislocker.o dislocker.c
In file included from dislocker.c:28:
In file included from ./accesses/accesses.h:27:
In file included from ./dislocker.h:29:
./encommon.h:34:10: fatal error: 'polarssl/aes.h' file not found
#include "polarssl/aes.h"
         ^
1 error generated.
make: *** [dislocker.o] Error 1

==> Downloading https://github.com/Aorimn/dislocker/archive/v0.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/dislocker-0.4.0.tar.gz
==> make -C src
#include "polarssl/aes.h"
         ^
1 error generated.
make: *** [dislocker.o] Error 1
make: *** Waiting for unfinished jobs....

I have to admit this is all very new to me, I have not used terminal much in Mac OS X.  I need to be able to access a Bitlocker encrypted USB drive to alter a PDF file (legitimately with a password).  I installed polarssl and homebrew.

**Comment by Aorimn** [comment]
Hi, sorry for being this late.

Is the version from the develop branch working for you?

**Comment by Aorimn** [comment]
FYI, the new released version should fix this issue.
