### ISSUE TITLE
cmake . fail

### ISSUE THREAD

**Issue by bmlikota** [Aorimn/dislocker#49]
I am trying to install dislocker from develop on ubuntu. I am getting errors. Please help

-------------------------------------------------------------------------------------------------------------------------
CMakeError.log
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: CMAKE_CXX_COMPILER-NOTFOUND 
Build flags: 
Id flags: 

The output was:
No such file or directory

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: CMAKE_CXX_COMPILER-NOTFOUND 
Build flags: 
Id flags: -c

The output was:
No such file or directory

Checking whether the CXX compiler is IAR using "" did not match "IAR .+ Compiler":
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: CMAKE_CXX_COMPILER-NOTFOUND 
Build flags: 
Id flags: 

The output was:
No such file or directory

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: CMAKE_CXX_COMPILER-NOTFOUND 
Build flags: 
Id flags: -c

The output was:
No such file or directory

Checking whether the CXX compiler is IAR using "" did not match "IAR .+ Compiler":
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: CMAKE_CXX_COMPILER-NOTFOUND 
Build flags: 
Id flags: 

The output was:
No such file or directory

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: CMAKE_CXX_COMPILER-NOTFOUND 
Build flags: 
Id flags: -c

The output was:
No such file or directory

Checking whether the CXX compiler is IAR using "" did not match "IAR .+ Compiler":

**Comment by bmlikota** [comment]
Additionaly

I have Ubuntu 14.04 LTS

Error occured after executing commands:
$ aptitude install gcc cmake make libfuse-dev libpolarssl-dev ruby-dev
$ cmake .

**Comment by Aorimn** [comment]
I just tested with an up-to-date Ubuntu 14.04 and everything is fine from my point of view.

Would you mind trying to `aptitude update && aptitude upgrade` your machine and if this still doesn't work, try to compile https://github.com/ARMmbed/mbedtls ? It's just an example of another project using cmake, in order to make sure it's a dislocker problem and not a cmake one.

**Comment by bmlikota** [comment]
I tried with mbedtls and this is the output:

~/MyTools$ cd mbedtls/
~/MyTools/mbedtls$ cmake .
-- The C compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bmlikota/MyTools/mbedtls
~/MyTools/mbedtls$

**Comment by Aorimn** [comment]
Did you give me everything from the cmake output on your first message?
Is your Ubuntu 32 or 64 bits? (`uname -a`)

**Comment by bmlikota** [comment]
Problem solved:
"Although you have to run `make' in the src directory on the stable release, on the develop release, the `cmake .' command is to be run in the "root" directory"

Thanks Aorimn (RC)

**Comment by Aorimn** [comment]
Great! :-)
