### ISSUE TITLE
The signature of the volume (м) doesn't match the BitLocker's ones (-FVE-FS- or MSWIN4.1). Abort.

### ISSUE THREAD

**Issue by thvasilo** [Aorimn/dislocker#50]
I'm trying to read a drive using the develop branch. The reported filesystem on the drive is HPFS/NTFS/exFAT

This is a WD My Passport drive, encrypted on Windows 8.1 with BitLockerToGo.

Any idea what might be causing this?

Edit: HPFS/NTFS/exFAT is the system that fdisk reports, lsblk does not show anything for the filesystem on the drive.

**Comment by Aorimn** [comment]
Hi @thvasilo 

This error is most probably due to an error while giving the drive to dislocker. Are you sure you're giving the encrypted partition to dislocker, and not the disk? What's the exact commandline you're using?

**Comment by thvasilo** [comment]
You are correct, I was trying to mount the whole drive instead of the partition. It works fine now.

**Comment by sh3lan93** [comment]
how to give encrypted partition to dislocker instead of the drive ?

**Comment by Aorimn** [comment]
You can use fdisk on the drive and look for the right partition. Once you get it (or in order to get it), you can use the `--offset` option of dislocker (multiplying the sector start number by the sector size).

For example, on a disk like the following one, let's say /dev/sda2 is BitLocker-encrypted:
```
# fdisk -l /dev/sda
Disk /dev/sda: 698.7 GiB, 750156374016 bytes, 1465149168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0xe3102a4b

Device     Boot     Start        End   Sectors   Size Id Type
/dev/sda1            2048   52430847  52428800    25G 1c Hidden W95 FAT32 (LBA)
/dev/sda2  *     52430848  638488575 586057728 279.5G  7 HPFS/NTFS/exFAT
/dev/sda3       638488576  639512575   1024000   500M 83 Linux
/dev/sda4       639512576 1465149167 825636592 393.7G  5 Extended
/dev/sda5       639514624 1465147391 825632768 393.7G 83 Linux
```

Then you can run dislocker in the following way (where 52430848 is the beginning sector number of the /dev/sda2 encrypted partition):
```
dislocker -V /dev/sda -o $((52430848 * 512)) -- /mnt/dislocker/
```
