### ISSUE TITLE
Library not found for -losxfuse_i64

### ISSUE THREAD

**Issue by niquedegraaff** [Aorimn/dislocker#53]
On dev build. (because the latest just wont work on 10.11).
I'm not entirely sure what i'm doing, just following the unstructions in install.mb. 
So yes, i got osxfuse and that mbedTLS thing installed. See result in screenshot.

![Screenshot of action](http://i.snag.gy/AQE5a.jpg)

**Comment by Aorimn** [comment]
I would need more information to reproduce the problem and help you fix this. How did you install osxfuse, with homebrew or through the sources?
Can you run this command: `find / -name 'osxfuse*' -ls` (quotes are important)?

**Comment by Aorimn** [comment]
FYI, the master branch should be okay now.
