### ISSUE TITLE
DESTDIR environment variable is ignored during installation

### ISSUE THREAD

**Issue by robert-scheck** [Aorimn/dislocker#54]
The DESTDIR environment variable is ignored during installation:

    […]
    -- Installing: /builddir/build/BUILDROOT/dislocker-0.5.1-1.fc24.x86_64/usr/lib64/libdislocker.so.0.5.1
    -- Installing: /builddir/build/BUILDROOT/dislocker-0.5.1-1.fc24.x86_64/usr/lib64/libdislocker.so.0.5
    -- Installing: /builddir/build/BUILDROOT/dislocker-0.5.1-1.fc24.x86_64/usr/lib64/libdislocker.so
    -- Installing: /builddir/build/BUILDROOT/dislocker-0.5.1-1.fc24.x86_64/usr/bin/dislocker-fuse
    -- Removed runtime path from "/builddir/build/BUILDROOT/dislocker-0.5.1-1.fc24.x86_64/usr/bin/dislocker-fuse"
    -- Installing: /builddir/build/BUILDROOT/dislocker-0.5.1-1.fc24.x86_64/usr/share/man/man1/dislocker-fuse.1.gz
    -- Installing: /builddir/build/BUILDROOT/dislocker-0.5.1-1.fc24.x86_64/usr/bin/dislocker-file
    -- Removed runtime path from "/builddir/build/BUILDROOT/dislocker-0.5.1-1.fc24.x86_64/usr/bin/dislocker-file"
    -- Installing: /builddir/build/BUILDROOT/dislocker-0.5.1-1.fc24.x86_64/usr/share/man/man1/dislocker-file.1.gz
    -- Installing: /builddir/build/BUILDROOT/dislocker-0.5.1-1.fc24.x86_64/usr/bin/dislocker-metadata
    -- Removed runtime path from "/builddir/build/BUILDROOT/dislocker-0.5.1-1.fc24.x86_64/usr/bin/dislocker-metadata"
    -- Installing: /builddir/build/BUILDROOT/dislocker-0.5.1-1.fc24.x86_64/usr/bin/dislocker-bek
    -- Removed runtime path from "/builddir/build/BUILDROOT/dislocker-0.5.1-1.fc24.x86_64/usr/bin/dislocker-bek"
    failed to create symbolic link '/usr/bin/dislocker': Permission denied
    failed to create symbolic link '/usr/share/man/man1/dislocker.1.gz': Permission denied
    […]

**Comment by Aorimn** [comment]
Thanks again for the PR.
