### ISSUE TITLE
fuse: bad mount point 'password' : No such file or directory.

### ISSUE THREAD

**Issue by mgardner28** [Aorimn/dislocker#62]
I have a recovery password that is supplied by our IT department. It is all numbers in the following format: XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX. I execute sudo dislocker -r -V /dev/sda1 -p XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX -- /media/windows
I get 5 lines on screen as follows:
Enter the recover password: "password I entered above"
Enter the recover password: "password I entered above"
Enter the recover password: "password I entered above"
Enter the recover password: "password I entered above"
Enter the recover password: "XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX" actual x's not the password.
Valid password format, continuing.
fuse: bad mount point 'password I entered': No such file or directory

What I am missing? Any help appreciated.

Thanks,
M

**Comment by Aorimn** [comment]
Hi,
I'm not sure why you get 5 lines in your output, put if you're going to use the password in the command line, you have to stick the password to the p option like so: `-pXXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX`.

Hope that helps, let me know if it doesn't.

**Comment by mgardner28** [comment]
Finally got back around to working on this. Not really sure how I messed it up before. Worked perfectly.

Thanks,
M

**Comment by Aorimn** [comment]
Great!
