### ISSUE TITLE
Recompile with -fPIC ?

### ISSUE THREAD

**Issue by tianlaizhiyin** [Aorimn/dislocker#64]
Hi Aorimn,
Can you help me? When I install this program,the problem got me stumped。

/usr/bin/ld: /usr/local/lib/libmbedcrypto.a(aes.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; 
/usr/local/lib/libmbedcrypto.a: could not read symbols: Bad value
collect2: ld 返回 1
make[2]: *** [src/libdislocker.so.0.6.1] 错误 1
make[1]: *** [src/CMakeFiles/dislocker.dir/all] 错误 2
make: *** [all] 错误 2

Thanks!

**Comment by Aorimn** [comment]
Hi @tianlaizhiyin 

It shouldn't happen as the library is already built with -fPIC. Which linux distro have you? Which gcc/clang version? Can you run `make clean && make VERBOSE=1` and paste it in order for me to help you debug this issue?

**Comment by tianlaizhiyin** [comment]
Yeah, I can found it built with -fPIC, but it still does not run correctly. 

> /usr/bin/cmake -E cmake_progress_report /filesys/share/dislocker-0.6.1/CMakeFiles 29
[ 87%] Building C object src/CMakeFiles/dislocker.dir/ruby.c.o
cd /filesys/share/dislocker-0.6.1/src && /usr/bin/cc  -DAUTHOR="\"Romain Coltel\"" -DPROGNAME=\"dislocker\" -DVERSION=\"0.6.1\" -DVERSION_DBG=\":\" -D_FILE_OFFSET_BITS=64 -D_HAVE_RUBY=1.8.7 -D__ARCH=\"x86_64\" -D__ARCH_X86_64 -D__LINUX -D__OS=\"Linux\" -Ddislocker_EXPORTS -fPIC -Wall -Werror -Wextra -fstack-protector -fstrict-aliasing -D_FORTIFY_SOURCE=2 -O1 -Wconversion -Wl,-z,now -Wl,-z,relro -fPIC -isystem /usr/local/include -I/filesys/share/dislocker-0.6.1/include -I/usr/lib64/ruby/1.8/x86_64-linux -I/usr/lib64/ruby/1.8/x86_64-linux/x86_64-linux -I/filesys/share/dislocker-0.6.1/src/nil/ruby-1.8.7    -o CMakeFiles/dislocker.dir/ruby.c.o   -c /filesys/share/dislocker-0.6.1/src/ruby.c
Linking C shared library libdislocker.so
cd /filesys/share/dislocker-0.6.1/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/dislocker.dir/link.txt --verbose=1
/usr/bin/cc  -fPIC  -fPIC -Wall -Werror -Wextra -fstack-protector -fstrict-aliasing -D_FORTIFY_SOURCE=2 -O1 -Wconversion -Wl,-z,now -Wl,-z,relro   -shared -Wl,-soname,libdislocker.so.0.6 -o libdislocker.so.0.6.1 CMakeFiles/dislocker.dir/dislocker.c.o CMakeFiles/dislocker.dir/common.c.o CMakeFiles/dislocker.dir/config.c.o CMakeFiles/dislocker.dir/xstd/xstdio.c.o CMakeFiles/dislocker.dir/xstd/xstdlib.c.o CMakeFiles/dislocker.dir/metadata/datums.c.o CMakeFiles/dislocker.dir/metadata/metadata.c.o CMakeFiles/dislocker.dir/metadata/vmk.c.o CMakeFiles/dislocker.dir/metadata/fvek.c.o CMakeFiles/dislocker.dir/metadata/extended_info.c.o CMakeFiles/dislocker.dir/metadata/guid.c.o CMakeFiles/dislocker.dir/metadata/print_metadata.c.o CMakeFiles/dislocker.dir/accesses/stretch_key.c.o CMakeFiles/dislocker.dir/accesses/accesses.c.o CMakeFiles/dislocker.dir/accesses/rp/recovery_password.c.o CMakeFiles/dislocker.dir/accesses/user_pass/user_pass.c.o CMakeFiles/dislocker.dir/accesses/bek/bekfile.c.o CMakeFiles/dislocker.dir/encryption/encommon.c.o CMakeFiles/dislocker.dir/encryption/decrypt.c.o CMakeFiles/dislocker.dir/encryption/encrypt.c.o CMakeFiles/dislocker.dir/encryption/diffuser.c.o CMakeFiles/dislocker.dir/encryption/crc32.c.o CMakeFiles/dislocker.dir/encryption/aes-xts.c.o CMakeFiles/dislocker.dir/ntfs/clock.c.o CMakeFiles/dislocker.dir/ntfs/encoding.c.o CMakeFiles/dislocker.dir/inouts/inouts.c.o CMakeFiles/dislocker.dir/inouts/prepare.c.o CMakeFiles/dislocker.dir/inouts/sectors.c.o CMakeFiles/dislocker.dir/ruby.c.o -lpthread /usr/local/lib/libmbedcrypto.a /usr/lib64/libruby.so -Wl,-rpath,:::::::::::::::: 
/usr/bin/ld: /usr/local/lib/libmbedcrypto.a(aes.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libmbedcrypto.a: could not read symbols: Bad value
collect2: ld 返回 1
make[2]: *** [src/libdislocker.so.0.6.1] 错误 1
make[2]: Leaving directory `/filesys/share/dislocker-0.6.1'
make[1]: *** [src/CMakeFiles/dislocker.dir/all] 错误 2
make[1]: Leaving directory `/filesys/share/dislocker-0.6.1'
make: *** [all] 错误 2

Thanks!

**Comment by Aorimn** [comment]
Indeed, but that doesn't give me your compiler version (`/usr/bin/cc --version`) nor your linux distribution. Can you please provide them so that I can try to reproduce the error?

**Comment by tianlaizhiyin** [comment]
Oh! Sorry, I forgot that. Is this version too old?

> [root@JefServ dislocker-0.6.1]# cc --version
cc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
Copyright © 2010 Free Software Foundation, Inc.

**Comment by Aorimn** [comment]
I'm not sure about the version, but it shouldn't be too old. Would it be possible to have your linux distribution (fedora, redhat, centos, etc.) in order to reproduce the problem?

**Comment by tianlaizhiyin** [comment]
Yeah

> LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.5 (Santiago)
Release:	6.5
Codename:	Santiago

**Comment by gfahb** [comment]
Hi Aorimn,
I have the same problem on ubuntu 14.04 TLS. Intel 64-Bit

**Comment by alokjadhav** [comment]
facing the same problem here. 

```
ubuntu@ubuntu:~/apps/dislocker$ cc --version
cc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ubuntu@ubuntu:~/apps/dislocker$ uname -a
Linux ubuntu 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```

Any update on this error?

**Comment by Aorimn** [comment]
Hi,
I can't seem to be able to reproduce the problem on Ubuntu 14.04 x64 on a fresh install:
http://pastie.org/10792802
Can someone with the problem on Ubuntu paste me something with the same commands as in this paste, replacing the `make` command with `make VERBOSE=1`, please?

I'll test on CentOS 6.5 when I have more time.

**Comment by gfahb** [comment]
root@hbmewl17:/dislocker/dislocker-0.6.1# make VERBOSE=1
/usr/bin/cmake -H/dislocker/dislocker-0.6.1 -B/dislocker/dislocker-0.6.1 --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /dislocker/dislocker-0.6.1/CMakeFiles /dislocker/dislocker-0.6.1/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/dislocker/dislocker-0.6.1'
make -f src/CMakeFiles/dislocker.dir/build.make src/CMakeFiles/dislocker.dir/depend
make[2]: Entering directory `/dislocker/dislocker-0.6.1'
cd /dislocker/dislocker-0.6.1 && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /dislocker/dislocker-0.6.1 /dislocker/dislocker-0.6.1/src /dislocker/dislocker-0.6.1 /dislocker/dislocker-0.6.1/src /dislocker/dislocker-0.6.1/src/CMakeFiles/dislocker.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/dislocker/dislocker-0.6.1'
make -f src/CMakeFiles/dislocker.dir/build.make src/CMakeFiles/dislocker.dir/build
make[2]: Entering directory `/dislocker/dislocker-0.6.1'
Linking C shared library libdislocker.so
cd /dislocker/dislocker-0.6.1/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/dislocker.dir/link.txt --verbose=1
/usr/bin/cc  -fPIC  -fPIC -Wall -Werror -Wextra -fstack-protector -fstrict-aliasing -D_FORTIFY_SOURCE=2 -O1 -Wconversion -Wl,-z,now -Wl,-z,relro   -shared -Wl,-soname,libdislocker.so.0.6 -o libdislocker.so.0.6.1 CMakeFiles/dislocker.dir/dislocker.c.o CMakeFiles/dislocker.dir/common.c.o CMakeFiles/dislocker.dir/config.c.o CMakeFiles/dislocker.dir/xstd/xstdio.c.o CMakeFiles/dislocker.dir/xstd/xstdlib.c.o CMakeFiles/dislocker.dir/metadata/datums.c.o CMakeFiles/dislocker.dir/metadata/metadata.c.o CMakeFiles/dislocker.dir/metadata/vmk.c.o CMakeFiles/dislocker.dir/metadata/fvek.c.o CMakeFiles/dislocker.dir/metadata/extended_info.c.o CMakeFiles/dislocker.dir/metadata/guid.c.o CMakeFiles/dislocker.dir/metadata/print_metadata.c.o CMakeFiles/dislocker.dir/accesses/stretch_key.c.o CMakeFiles/dislocker.dir/accesses/accesses.c.o CMakeFiles/dislocker.dir/accesses/rp/recovery_password.c.o CMakeFiles/dislocker.dir/accesses/user_pass/user_pass.c.o CMakeFiles/dislocker.dir/accesses/bek/bekfile.c.o CMakeFiles/dislocker.dir/encryption/encommon.c.o CMakeFiles/dislocker.dir/encryption/decrypt.c.o CMakeFiles/dislocker.dir/encryption/encrypt.c.o CMakeFiles/dislocker.dir/encryption/diffuser.c.o CMakeFiles/dislocker.dir/encryption/crc32.c.o CMakeFiles/dislocker.dir/encryption/aes-xts.c.o CMakeFiles/dislocker.dir/ntfs/clock.c.o CMakeFiles/dislocker.dir/ntfs/encoding.c.o CMakeFiles/dislocker.dir/inouts/inouts.c.o CMakeFiles/dislocker.dir/inouts/prepare.c.o CMakeFiles/dislocker.dir/inouts/sectors.c.o CMakeFiles/dislocker.dir/ruby.c.o -lpthread /usr/local/lib/libmbedcrypto.a /usr/lib/libruby-1.9.1.so -Wl,-rpath,:::::::::::::: 
/usr/bin/ld: /usr/local/lib/libmbedcrypto.a(aes.c.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libmbedcrypto.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [src/libdislocker.so.0.6.1] Error 1
make[2]: Leaving directory `/dislocker/dislocker-0.6.1'
make[1]: *** [src/CMakeFiles/dislocker.dir/all] Error 2
make[1]: Leaving directory `/dislocker/dislocker-0.6.1'
make: *** [all] Error 2

**Comment by alokjadhav** [comment]
I guess I will try an older version of Ubuntu. Any suggestions which version will work? which version of Ubuntu did you use? I will try that. Please note I am using the Ubuntu live CD.

**Comment by Aorimn** [comment]
I've used Ubuntu 14.04 for the above logs, also from the liveCD.

**Comment by alokjadhav** [comment]
I had tried with 14.04-4.
 I am going to try again with kubuntu 14.04 this time. will update the issue here.

**Comment by Aorimn** [comment]
The exact version I tested was ubuntu-14.04.1. I'll try to reproduce with the 14.04-4.

**Comment by Xonman** [comment]
For those still having this issue, I just ran up against it in Ubuntu Xenial and discovered it's actually an issue with the way PolarSSL has been compiled. By recompiling polar from source with the -fpie and -fPIC I was able to get dislocker to compile happily.

**Comment by Aorimn** [comment]
Thanks for the insight @Xonman, I'll close this bug then.
