### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by francoislm** [Aorimn/dislocker#65]
Hello

Im trying using this command : dislocker -r -V /dev/sda2 -uXXXXX -- /media/bitlocker
I get this error : 
 [CRITICAL] None of the provided decryption mean is decrypting the keys. Abort.
 [CRITICAL] Unable to grab VMK or FVEK. Abort.
I run the command on Ubuntu live (on USB key).
Normally booting Windows after the BIOS the bitlocker asks me the numeric password using the Fn keys of the keyboard. In the Ubuntu terminal I type the password with the standard numeric keys. Can it be the origin of the trouble ?

**Comment by Aorimn** [comment]
Hi @francoislm 

This is probably due to the fact that you use the TPM, which is not currently supported by dislocker. If you want to be more sure, let me see the output with -vvvv passed to dislocker (don't to put the real password in the commandline).

**Comment by francoislm** [comment]
Hello,

The roadmap of Dislocker includes the support of TPM? When ?

By advance, thank you
François M.

**Comment by Aorimn** [comment]
It's tricky so it's in the roadmap, but there's no deadline to it. Also, by default and if I understand correctly, the TPM protects against decrypting/mounting BitLocker partitions from another OS than Windows.

**Comment by mayureshmayur** [comment]
[root@mayureshmayur dislocker-0.7.1]# dislocker -r -V /dev/sdb1 -p -- /media/Drive1/
Enter the recovery password: XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX
Valid password format, continuing.
Sun Nov 5 03:02:22 2017 [CRITICAL] None of the provided decryption mean is decrypting the keys. Abort.
Sun Nov 5 03:02:22 2017 [CRITICAL] Unable to grab VMK or FVEK. Abort.

Not able to solve this. Can anyone help?

**Comment by VasoVV** [comment]
Using TPM with Bitclocker still makes linux system helpless for rescuing Windows OS after virus attack.

`$ sudo dislocker -r -V /dev/sda6 -p -- /mnt/sda6
Enter the recovery password: XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX
Valid password format, continuing.
Wed Jan  2 17:01:36 2019 [CRITICAL] None of the provided decryption mean is decrypting the keys. Abort.
Wed Jan  2 17:01:36 2019 [CRITICAL] Unable to grab VMK or FVEK. Abort.`

**Comment by Aorimn** [comment]
After further investigations, if your partition is encrypted using the TPM, dislocker cannot do anything about it.

**Comment by Arz4te** [comment]
Hi!!! I'm having problems.  The line im showing to you is: tristan@arqquinn:~$ sudo dislocker -vvvv -V /dev/sda2 -uPASSWORD -- /media/bitlocker/

Can you help me??

Sun Jan 24 21:55:47 2021 [DEBUG] Verbosity level to DEBUG (4) into 'stdout'
Sun Jan 24 21:55:47 2021 [INFO] dislocker by Romain Coltel, v0.7.1 (compiled for Linux/x86_64)
Sun Jan 24 21:55:47 2021 [DEBUG] --- Config...
Sun Jan 24 21:55:47 2021 [DEBUG]    Verbosity: 4
Sun Jan 24 21:55:47 2021 [DEBUG]    Trying to decrypt '/dev/sda2'
Sun Jan 24 21:55:47 2021 [DEBUG]    	using the user's password method
Sun Jan 24 21:55:47 2021 [DEBUG]    		-> 'jima910522'
Sun Jan 24 21:55:47 2021 [DEBUG]    Using the first valid metadata block
Sun Jan 24 21:55:47 2021 [DEBUG] ... End config ---
Sun Jan 24 21:55:47 2021 [DEBUG] Trying to open '/dev/sda2'...
Sun Jan 24 21:55:47 2021 [DEBUG] Trying to open '/dev/sda2'...
Sun Jan 24 21:55:47 2021 [DEBUG] Opened (fd #3).
Sun Jan 24 21:55:47 2021 [DEBUG] Opened (fd #3).
Sun Jan 24 21:55:47 2021 [DEBUG] New memory allocation at 0x560708e2ceb0 (0x18 bytes allocated)
Sun Jan 24 21:55:47 2021 [DEBUG] New memory allocation at 0x560708e2ced0 (0x90 bytes allocated)
Sun Jan 24 21:55:47 2021 [DEBUG] New memory allocation at 0x560708e2b380 (0x200 bytes allocated)
Sun Jan 24 21:55:47 2021 [DEBUG] Positioning #3 at offset 0 from 0
Sun Jan 24 21:55:47 2021 [DEBUG] Reading volume header...
Sun Jan 24 21:55:47 2021 [DEBUG] Reading 0x200 bytes from #3 into 0x560708e2b380
Sun Jan 24 21:55:48 2021 [DEBUG] Volume header read
Sun Jan 24 21:55:48 2021 [DEBUG] =====[ Volume header information ]=====
Sun Jan 24 21:55:48 2021 [DEBUG]   Signature: '-FVE-FS-'
Sun Jan 24 21:55:48 2021 [DEBUG]   Sector size: 0x0200 (512) bytes
Sun Jan 24 21:55:48 2021 [DEBUG]   Sector per cluster: 0x08 (8) bytes
Sun Jan 24 21:55:48 2021 [DEBUG]   Reserved clusters: 0x0000 (0) bytes
Sun Jan 24 21:55:48 2021 [DEBUG]   Fat count: 0x00 (0) bytes
Sun Jan 24 21:55:48 2021 [DEBUG]   Root entries: 0x0000 (0) bytes
Sun Jan 24 21:55:48 2021 [DEBUG]   Number of sectors (16 bits): 0x0000 (0) bytes
Sun Jan 24 21:55:48 2021 [DEBUG]   Media descriptor: 0xf8 (248) bytes
Sun Jan 24 21:55:48 2021 [DEBUG]   Sectors per fat: 0x0000 (0) bytes
Sun Jan 24 21:55:48 2021 [DEBUG]   Hidden sectors: 0x00040800 (264192) bytes
Sun Jan 24 21:55:48 2021 [DEBUG]   Number of sectors (32 bits): 0x00000000 (0) bytes
Sun Jan 24 21:55:48 2021 [DEBUG]   Number of sectors (64 bits): 0x0000000000000000 (0) bytes
Sun Jan 24 21:55:48 2021 [DEBUG]   MFT start cluster: 0x0000000000060001 (393217) bytes
Sun Jan 24 21:55:48 2021 [DEBUG]   Metadata Lcn: 0x0000000000000000 (0) bytes
Sun Jan 24 21:55:48 2021 [DEBUG]   Volume GUID: '4967D63B-2E29-4AD8-8399-F6A339E3D001'
Sun Jan 24 21:55:48 2021 [DEBUG]   First metadata header offset:  0x0000000009500000
Sun Jan 24 21:55:48 2021 [DEBUG]   Second metadata header offset: 0x0000000049500000
Sun Jan 24 21:55:48 2021 [DEBUG]   Third metadata header offset:  0x0000000089500000
Sun Jan 24 21:55:48 2021 [DEBUG]   Boot Partition Identifier: '0xaa55'
Sun Jan 24 21:55:48 2021 [DEBUG] ========================================
Sun Jan 24 21:55:48 2021 [INFO] Volume GUID (INFORMATION OFFSET) supported
Sun Jan 24 21:55:48 2021 [DEBUG] Entering get_metadata_lazy_checked
Sun Jan 24 21:55:48 2021 [DEBUG] Positioning #3 at offset 156237824 from 0
Sun Jan 24 21:55:48 2021 [DEBUG] Reading bitlocker header at 0x9500000...
Sun Jan 24 21:55:48 2021 [DEBUG] Reading 0x70 bytes from #3 into 0x7ffc64d33170
Sun Jan 24 21:55:48 2021 [DEBUG] New memory allocation at 0x560708e2cf70 (0x380 bytes allocated)
Sun Jan 24 21:55:48 2021 [DEBUG] Reading data...
Sun Jan 24 21:55:48 2021 [DEBUG] Reading 0x310 bytes from #3 into 0x560708e2cfe0
Sun Jan 24 21:55:48 2021 [DEBUG] End get_metadata.
Sun Jan 24 21:55:48 2021 [DEBUG] Reading validations data at offset 0x9500380.
Sun Jan 24 21:55:48 2021 [DEBUG] Positioning #3 at offset 156238720 from 0
Sun Jan 24 21:55:48 2021 [DEBUG] Reading 0x8 bytes from #3 into 0x7ffc64d33238
Sun Jan 24 21:55:48 2021 [DEBUG] Looking if 0xe2036191 == 0xe2036191 for metadata validation
Sun Jan 24 21:55:48 2021 [DEBUG] We have a winner (n°1)!
Sun Jan 24 21:55:48 2021 [INFO] BitLocker metadata found and parsed.
Sun Jan 24 21:55:48 2021 [DEBUG] =====================[ BitLocker information structure ]=====================
Sun Jan 24 21:55:48 2021 [DEBUG]   Signature: '-FVE-FS-'
Sun Jan 24 21:55:48 2021 [DEBUG]   Total Size: 0x0380 (896) bytes (including signature and data)
Sun Jan 24 21:55:48 2021 [DEBUG]   Version: 2
Sun Jan 24 21:55:48 2021 [DEBUG]   Current state: ENCRYPTED (4)
Sun Jan 24 21:55:48 2021 [DEBUG]   Next state: ENCRYPTED (4)
Sun Jan 24 21:55:48 2021 [DEBUG]   Encrypted volume size: 1000068874240 bytes (0xe8d8c00000), ~953740 MB
Sun Jan 24 21:55:48 2021 [DEBUG]   Size of conversion region: 0 (0)
Sun Jan 24 21:55:48 2021 [DEBUG]   Number of boot sectors backuped: 16 sectors (0x10)
Sun Jan 24 21:55:48 2021 [DEBUG]   First metadata header offset:  0x9500000
Sun Jan 24 21:55:48 2021 [DEBUG]   Second metadata header offset: 0x49500000
Sun Jan 24 21:55:48 2021 [DEBUG]   Third metadata header offset:  0x89500000
Sun Jan 24 21:55:48 2021 [DEBUG]   Boot sectors backup address:   0x9510000
Sun Jan 24 21:55:48 2021 [DEBUG] New memory allocation at 0x560708e2d300 (0xc bytes allocated)
Sun Jan 24 21:55:48 2021 [DEBUG]   ----------------------------{ Dataset header }----------------------------
Sun Jan 24 21:55:48 2021 [DEBUG]     Dataset size: 0x00000338 (824) bytes (including data)
Sun Jan 24 21:55:48 2021 [DEBUG]     Unknown data: 0x00000001 (always 0x00000001)
Sun Jan 24 21:55:48 2021 [DEBUG]     Dataset header size: 0x00000030 (always 0x00000030)
Sun Jan 24 21:55:48 2021 [DEBUG]     Dataset copy size: 0x00000338 (824) bytes
Sun Jan 24 21:55:48 2021 [DEBUG]     Dataset GUID: 'F92C8B6D-31E5-4FB2-8129-B7B991792339'
Sun Jan 24 21:55:48 2021 [DEBUG]     Next counter: 21
Sun Jan 24 21:55:48 2021 [DEBUG]     Encryption Type: AES-XTS-128 (0x8004)
Sun Jan 24 21:55:48 2021 [DEBUG]     Epoch Timestamp: 1579064236 sec, that to say Wed Jan 15 04:57:16 2020
Sun Jan 24 21:55:48 2021 [DEBUG]   --------------------------------------------------------------------------
Sun Jan 24 21:55:48 2021 [DEBUG] Freeing pointer at address 0x560708e2d300
Sun Jan 24 21:55:48 2021 [DEBUG] =============================================================================
Sun Jan 24 21:55:48 2021 [DEBUG] Header safe: 0x48, 0x7, 0x2, 0x1
Sun Jan 24 21:55:48 2021 [DEBUG] 
Sun Jan 24 21:55:48 2021 [DEBUG] =======[ Datum n°1 information ]=======
Sun Jan 24 21:55:48 2021 [DEBUG] Total datum size: 0x0048 (72) bytes
Sun Jan 24 21:55:48 2021 [DEBUG] Datum entry type: 7
Sun Jan 24 21:55:48 2021 [DEBUG]    `--> ENTRY TYPE UNKNOWN
Sun Jan 24 21:55:48 2021 [DEBUG] Datum value type: 2
Sun Jan 24 21:55:48 2021 [DEBUG]    `--> UNICODE -- Total size header: 8 -- Nested datum: no
Sun Jan 24 21:55:48 2021 [DEBUG] Status: 0x1
Sun Jan 24 21:55:48 2021 [DEBUG] New memory allocation at 0x560708e2d350 (0x80 bytes allocated)
Sun Jan 24 21:55:48 2021 [DEBUG] UTF-16 string: 'DESKTOP-05Q0CAT DATA 14/01/2020'
Sun Jan 24 21:55:48 2021 [DEBUG] Freeing pointer at address 0x560708e2d350
Sun Jan 24 21:55:48 2021 [DEBUG] =========================================
Sun Jan 24 21:55:48 2021 [DEBUG] Header safe: 0x50, 0x3, 0x5, 0x1
Sun Jan 24 21:55:48 2021 [DEBUG] 
Sun Jan 24 21:55:48 2021 [DEBUG] =======[ Datum n°2 information ]=======
Sun Jan 24 21:55:48 2021 [DEBUG] Total datu
