### ISSUE TITLE
Do not found the package in Homebrew

### ISSUE THREAD

**Issue by louisdecharson** [Aorimn/dislocker#66]
Hi,
I've searched for the packages in Homebrew, but was not able to find it.
`$ brew install src/dislocker.rb` returns 
`Error: No available formula with the name "dislocker"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...`

And dislocker can not be found either on [braumeister](http://braumeister.org/search/dislocker).

I've tried to do it _manually_ by following the **mbedTLS 2.0.0** subsection but I got confused after _You can then resume the installation where you have left it._

**Comment by Aorimn** [comment]
Hi,
The dislocker package hasn't been submitted to the Homebrew project, you'll have to download the 0.6.1 archive and run the `brew install src/dislocker.rb` command.
Here's what I get:
```
localhost:dislocker $ git branch
  develop
* master
localhost:dislocker $ git pull
Already up-to-date.
localhost:dislocker $ brew install src/dislocker.rb
==> Installing dependencies for dislocker: polarssl, cmake
==> Installing dislocker dependency: polarssl
==> Downloading https://homebrew.bintray.com/bottles/mbedtls-2.2.1.mavericks.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/mbedtls-2.2.1.mavericks.bottle.tar.gz
==> Pouring mbedtls-2.2.1.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/mbedtls/2.2.1: 114 files, 9.5M
==> Installing dislocker dependency: cmake
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.5.1.mavericks.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/cmake-3.5.1.mavericks.bottle.tar.gz
==> Pouring cmake-3.5.1.mavericks.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> Summary
🍺  /usr/local/Cellar/cmake/3.5.1: 2,010 files, 28M
==> Installing dislocker
==> Downloading https://github.com/Aorimn/dislocker/archive/v0.6.zip
Already downloaded: /Library/Caches/Homebrew/dislocker-0.6.0.zip
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PRE
==> make
==> make install
🍺  /usr/local/Cellar/dislocker/0.6.0: 18 files, 294.9K, built in 25 seconds
```

If you don't get this kind of output, please update brew (`brew update`) before trying again. You shouldn't have to follow the **mbedTLS 2.0.0** subsection as the mbedTLS package in Homebrew has been updated.

**Comment by louisdecharson** [comment]
Hi thanks so much for your reply. It worked like a charm !

**Comment by Aorimn** [comment]
Great!
