### ISSUE TITLE
Passing options from fstab

### ISSUE THREAD

**Issue by eaaltonen** [Aorimn/dislocker#68]
I would like to configure an fstab entry for dislocker.

I added a symlink `mount.dislocker -> /usr/local/bin/dislocker-fuse` and then added the fstab entry

```
/dev/sda2 /mnt/bitlocker/dislocker-file fuse.dislocker V=/dev/sda2,F=/path/to/key
```

However

```
# mount /mnt/bitlocker/dislocker-file
```

complains that

```
[CRITICAL] No BitLocker volume path given. Abort.
```

Is there a way to pass the required options from fstab?

**Comment by Aorimn** [comment]
Hi, it doesn't seem to be possible right now. I'll work on it as soon as I have some time.

**Comment by Aorimn** [comment]
Hi,
The develop branch has been updated with a version of dislocker which should support the fstab format, but with long options. To take back your example line, that would give this:
```
/dev/sda2 /mnt/bitlocker/ fuse.dislocker bekfile=/path/to/key 0 0
```

**Comment by eaaltonen** [comment]
Hi,
Tested with ec03dafe6a1e7cbcc925630ba7816205484e5444. Works great, thanks!

**Comment by mzdacuda** [comment]
Hi,
great to read that this is working now. Will there be a release with this fix soon? I am very interested in the fix but don't want to risk running a develop build on important data.
Thanks for the info!

**Comment by Aorimn** [comment]
Hi,
There will be a release, which will include this feature, as soon as other issues are answered for.

**Comment by Aorimn** [comment]
Hi,
This should be fixed now, as a new version is out.
