### ISSUE TITLE
installaion issue on ubuntu 14.04

### ISSUE THREAD

**Issue by tiho2** [Aorimn/dislocker#70]
Following installation instructions got an issue with `make` execution:
```
/tmp/dislocker/src$ sudo make
make: *** No targets specified and no makefile found.  Stop.
```

How to solve this issue? I hopped to install it quickly to get files from encrypted memory stick.

**Comment by Aorimn** [comment]
Hi,
You need to go in the /tmp/dislocker directory and run `cmake .`. Then, if everything's fine, you can run `make` and `make install`.

I don't know which installation instruction you're reading, but it seems they're outdated.

**Comment by tiho2** [comment]
You have right, instructions I've used, suggested installation from src folder: http://askubuntu.com/questions/617950/use-windows-bitlocker-encrypted-drive-on-ubuntu-14-04-lts

Installation is done now. Thanks for hint.

Unfortunatelly, didn't manage to mount the memory stick yet. Got an error that head could not be read. But that is now another subject and this computor is not avalable at the moment, so I don't have exact error message.

**Comment by Aorimn** [comment]
Ah, these instructions are indeed out-of-date.
Don't hesitate to paste me the output of dislocker with `-vvvv` for me to help you.

**Comment by tiho2** [comment]
Hi, thx for the answer!

The console output follows:
```
~$ sudo dislocker -vvv -V /dev/sdb  -pPASSWORD -- /media/bitlocker/
[sudo] password for userx: 
Mon Apr 11 18:31:49 2016 [INFO] dislocker by Romain Coltel, v0.5.1 (compiled for Linux/x86_64)
Mon Apr 11 18:31:49 2016 [INFO] Compiled version: :
Mon Apr 11 18:31:49 2016 [ERROR] The signature of the volume (м) doesn't match the BitLocker's ones (-FVE-FS- or MSWIN4.1). Abort.
Mon Apr 11 18:31:49 2016 [CRITICAL] Cannot parse volume header. Abort
```

**Comment by Aorimn** [comment]
This is most probably due the fact that you're giving /dev/sdb and not /dev/sdb1. The dislocker-find utility gives you, by default, a list of encrypted drives, thus should report /dev/sdb1.

**Comment by tiho2** [comment]
`/dev/sdb1` also didn't work:

```
sudo dislocker -vvv -V /dev/sdb1  -pPASSWORD -- /media/bitlocker/
[sudo] password for userx: 
Mon Apr 11 19:21:03 2016 [INFO] dislocker by Romain Coltel, v0.5.1 (compiled for Linux/x86_64)
Mon Apr 11 19:21:03 2016 [INFO] Compiled version: :
Mon Apr 11 19:21:03 2016 [INFO] Volume GUID (INFORMATION OFFSET) supported
Mon Apr 11 19:21:03 2016 [INFO] BitLocker metadata found and parsed.
Mon Apr 11 19:21:03 2016 [ERROR] Error handling the recovery password: Wrong length (has to be 55)
Mon Apr 11 19:21:03 2016 [ERROR] Error computing the recovery password to the recovery key. Abort.
Mon Apr 11 19:21:03 2016 [CRITICAL] None of the provided decryption mean is decrypting the keys. Abort.
Mon Apr 11 19:21:03 2016 [CRITICAL] Unable to grab VMK or FVEK. Abort.
```

**Comment by Aorimn** [comment]
This is actually better: `/dev/sdb1` is a BitLocker-encrypted partition. However, the password you're giving dislocker is not the recovery password. Maybe `-u` is the option you want, maybe you're using the TPM and dislocker won't be able to decrypt your volume.

**Comment by tiho2** [comment]
weeee! It works finally! Many thanks!

For now I've mounted it following instructions from ask ubuntu. It is mountes with root perimitions. But now I can exchange files when file manager with root permitions is opened.

I have earlier tried with both combinations `-u` and `-p` for `/dev/sdb` but only `-p` for `/dev/sdb1`. :)

Just in case, I'm posting final terminal output:
```
sudo dislocker -vvv -V /dev/sdb1  -uPASSWORD -- /media/bitlocker/
[sudo] password for userx: 
Mon Apr 11 20:25:06 2016 [INFO] dislocker by Romain Coltel, v0.5.1 (compiled for Linux/x86_64)
Mon Apr 11 20:25:06 2016 [INFO] Compiled version: :
Mon Apr 11 20:25:06 2016 [INFO] Volume GUID (INFORMATION OFFSET) supported
Mon Apr 11 20:25:06 2016 [INFO] BitLocker metadata found and parsed.
Mon Apr 11 20:25:06 2016 [INFO] Stretching the user password, it could take some time...
Mon Apr 11 20:25:07 2016 [INFO] Stretching of the user password is now ok!
Mon Apr 11 20:25:07 2016 [INFO] Used user password decryption method
Mon Apr 11 20:25:07 2016 [INFO] Found volume's size: 0x39d110000 (15520038912) bytes
Mon Apr 11 20:25:07 2016 [INFO] Running FUSE with these arguments: 
Mon Apr 11 20:25:07 2016 [INFO]   `--> 'dislocker'
Mon Apr 11 20:25:07 2016 [INFO]   `--> '/media/bitlocker/'
laptopname:~$ sudo -i
laptopname:~# cd /media/bitlocker
laptopname:/media/bitlocker# mount -o loop dislocker-file /media/mount
laptopname:/media/bitlocker# gksu nautilus /etc/apt/

``` 

Thanks! Cheers!

**Comment by Aorimn** [comment]
I'm glad it works for you, well done!
