### ISSUE TITLE
Ubuntu 16.04 & libpolarssl-dev

### ISSUE THREAD

**Issue by JosefRypacek** [Aorimn/dislocker#76]
Hi,

new ubuntu 16.04 does not allow me to install libpolarssl-dev. Repository doesn't contain polarssl anymore. Is there any way how to use this perfect project again?

Thanks a lot
Josef

**Comment by Aorimn** [comment]
Hi,

The library is now called libmbedtls-dev, following the renaming of polarssl to mbedtls. If you're not finding it in the default repositories, it might be in the universe or multiverse repositories.

**Comment by JosefRypacek** [comment]
Hi, thanks for your reply. 
I've installed this package but I still get errors while trying to install dislocker. I also tried commands is section "mbedTLS 2.0.0" from INSTALL.md

```
cc: error: /usr/lib/libpolarssl.so: No such file or directory
CMake Error at cmake/FindPolarSSL.cmake:71 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  src/CMakeLists.txt:109 (find_package)
```

**Comment by JosefRypacek** [comment]
It seems that something was cached and I have to delete & checkout again git repository. It works like a charm now.
