### ISSUE TITLE
Can't get metadata in FreeBSD

### ISSUE THREAD

**Issue by Heavenser** [Aorimn/dislocker#81]
I use cmake and gmake to compile and install dislocker on FreeBSD，but it can't get metadata.
debug info:
Wed Jul 13 19:15:27 2016 [INFO] Volume GUID (INFORMATION OFFSET) supported
Wed Jul 13 19:15:27 2016 [DEBUG] Entering get_metadata_lazy_checked
Wed Jul 13 19:15:27 2016 [DEBUG] Positionnong #3 at offset 473288704 from 0
Wed Jul 13 19:15:27 2016 [DEBUG] Reading bitlocker header at 0x1c35d000...
Wed Jul 13 19:15:27 2016 [DEBUG] Reading 0x70 bytes from #3 into 0x7fffffffe920
Wed Jul 13 19:15:27 2016 [ERROR] Failed to read in #3: Invalid argument
Wed Jul 13 19:15:27 2016 [ERROR] get_metadata::Error, not all bytes read: -1, 112 expected (1).
Wed Jul 13 19:15:27 2016 [ERROR] Can't get metadata (n��1)
Wed Jul 13 19:15:27 2016 [CRITICAL] A problem occured during the retrieving of metadata. Abort.
Wed Jul 13 19:15:27 2016 [CRITICAL] Can't initialize dislocker. Abort.

**Comment by Aorimn** [comment]
Hi, which dislocker's version are you using? Can you provide reproducible test data?

**Comment by Heavenser** [comment]
Hi, the version of dislocker is 0.6.1 , When this command is executed:
`sudo dislocker -u -V /dev/ada1p5 -p<(cat <(gpg --decrypt /home/heavenser/Other/recovery.key)) -- /media/BitLocker` 
return “[CRITICAL] A problem occured during the retrieving of metadata. Abort.“

and the complete debug info by  `sudo dislocker-metadata -v -V /dev/ada1p5`:
Thu Jul 14 03:33:10 2016 [DEBUG] Verbosity level to DEBUG (4) into 'stdout'
Thu Jul 14 03:33:10 2016 [INFO] dislocker by Romain Coltel, v0.6.1 (compiled for FreeBSD/x86_64)
Thu Jul 14 03:33:10 2016 [INFO] Compiled version: master:bcc8ed8
Thu Jul 14 03:33:10 2016 [DEBUG] Trying to open '/dev/ada1p5'...
Thu Jul 14 03:33:10 2016 [DEBUG] Trying to open '/dev/ada1p5'...
Thu Jul 14 03:33:10 2016 [DEBUG] Opened (fd #3).
Thu Jul 14 03:33:10 2016 [DEBUG] New memory allocation at 0x803c18040 (0x18 bytes allocated)
Thu Jul 14 03:33:10 2016 [DEBUG] New memory allocation at 0x803c19020 (0x90 bytes allocated)
Thu Jul 14 03:33:10 2016 [DEBUG] New memory allocation at 0x803c1b200 (0x200 bytes allocated)
Thu Jul 14 03:33:10 2016 [DEBUG] Positionnong #3 at offset 0 from 0
Thu Jul 14 03:33:10 2016 [DEBUG] Reading volume header...
Thu Jul 14 03:33:10 2016 [DEBUG] Reading 0x200 bytes from #3 into 0x803c1b200
Thu Jul 14 03:33:10 2016 [DEBUG] Volume header read
Thu Jul 14 03:33:10 2016 [DEBUG] =====[ Volume header informations ]=====
Thu Jul 14 03:33:10 2016 [DEBUG]   Signature: '-FVE-FS-'
Thu Jul 14 03:33:10 2016 [DEBUG]   Sector size: 0x0200 (512) bytes
Thu Jul 14 03:33:10 2016 [DEBUG]   Sector per cluster: 0x08 (8) bytes
Thu Jul 14 03:33:10 2016 [DEBUG]   Reserved clusters: 0x0000 (0) bytes
Thu Jul 14 03:33:10 2016 [DEBUG]   Fat count: 0x00 (0) bytes
Thu Jul 14 03:33:10 2016 [DEBUG]   Root entries: 0x0000 (0) bytes
Thu Jul 14 03:33:10 2016 [DEBUG]   Number of sectors (16 bits): 0x0000 (0) bytes
Thu Jul 14 03:33:10 2016 [DEBUG]   Media descriptor: 0xf8 (248) bytes
Thu Jul 14 03:33:10 2016 [DEBUG]   Sectors per fat: 0x0000 (0) bytes
Thu Jul 14 03:33:10 2016 [DEBUG]   Hidden sectors: 0x09800800 (159385600) bytes
Thu Jul 14 03:33:10 2016 [DEBUG]   Number of sectors (32 bits): 0x00000000 (0) bytes
Thu Jul 14 03:33:10 2016 [DEBUG]   Number of sectors (64 bits): 0x0000000000000000 (0) bytes
Thu Jul 14 03:33:10 2016 [DEBUG]   MFT start cluster: 0x0000000000060001 (393217) bytes
Thu Jul 14 03:33:10 2016 [DEBUG]   Metadata Lcn: 0x0000000000000000 (0) bytes
Thu Jul 14 03:33:10 2016 [DEBUG]   Volume GUID: '4967D63B-2E29-4AD8-8399-F6A339E3D001'
Thu Jul 14 03:33:10 2016 [DEBUG]   First metadata header offset:  0x000000001c35d000
Thu Jul 14 03:33:10 2016 [DEBUG]   Second metadata header offset: 0x0000000082326000
Thu Jul 14 03:33:10 2016 [DEBUG]   Third metadata header offset:  0x0000000086aad000
Thu Jul 14 03:33:10 2016 [DEBUG]   Boot Partition Identifier: '0xaa55'
Thu Jul 14 03:33:10 2016 [DEBUG] ========================================
Thu Jul 14 03:33:10 2016 [INFO] Volume GUID (INFORMATION OFFSET) supported
Thu Jul 14 03:33:10 2016 [DEBUG] Entering get_metadata_lazy_checked
Thu Jul 14 03:33:10 2016 [DEBUG] Positionnong #3 at offset 473288704 from 0
Thu Jul 14 03:33:10 2016 [DEBUG] Reading bitlocker header at 0x1c35d000...
Thu Jul 14 03:33:10 2016 [DEBUG] Reading 0x70 bytes from #3 into 0x7fffffffe9d0
Thu Jul 14 03:33:10 2016 [ERROR] Failed to read in #3: Invalid argument
Thu Jul 14 03:33:10 2016 [ERROR] get_metadata::Error, not all bytes read: -1, 112 expected (1).
Thu Jul 14 03:33:10 2016 [ERROR] Can't get metadata (n��1)
Thu Jul 14 03:33:10 2016 [CRITICAL] A problem occured during the retrieving of metadata. Abort.
Thu Jul 14 03:33:10 2016 [CRITICAL] Can't initialize dislocker. Abort.

**Comment by Aorimn** [comment]
Wow, "Invalid argument", that's weird. Thanks for the trace, I'll try to reproduce the problem.

**Comment by Aorimn** [comment]
Hi,
Sorry for making you wait. The issue was that FreeBSD devices don't accept random reads, only a block at a time, which doesn't happen while reading a regular file, as I was doing in my tests.
This issue should now be fixed on the develop branch.

**Comment by Heavenser** [comment]
Thank you!

**Comment by Aorimn** [comment]
Hi,
This should be fixed now, as a new version is out.
