### ISSUE TITLE
Can't prepare the crypt structure. Abort.

### ISSUE THREAD

**Issue by sterlingarcher1969** [Aorimn/dislocker#83]
My Windows 10 Pro decided to request the Bitlocker Recovery Key following some patch installs. I tried the correct key but it doesn't recover.

I've installed Dislocker on an Ubuntu partition, and it accepts the key.

It then displays the following message:

[CRITICAL] Can't prepare the crypt structure. Abort.

Is there any chance of recovering the data, or should I give up all hope?!!

Thanks in advance,

Rob

**Comment by Aorimn** [comment]
Could you please run the dislocker command with a verbose output (passing `-vvvv` to the dislocker commandline) and paste it here please? It will help me diagnose the issue.

**Comment by rea-al** [comment]
I'm getting the same error, take a look to the attached logs.
[log.txt](https://github.com/Aorimn/dislocker/files/1014967/log.txt)

**Comment by Aorimn** [comment]
Volume's size computation has been changed in v0.7.3, which has just been released, please try with this lastest version.
