### ISSUE TITLE
ntfs-3g-mount: mount failed: Permission denied

### ISSUE THREAD

**Issue by vipzrx** [Aorimn/dislocker#86]
$ sudo fdisk -l
Partition table entries are not in disk order.
Disk /dev/sdb: 931.5 GiB, 1000204885504 bytes, 1953525167 sectors
Units: sectors of 1 \* 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xe0f1c2e7

Device     Boot Start        End    Sectors   Size Id Type
/dev/sdb1        2048 1953521663 1953519616 931.5G  7 HPFS/NTFS/exFAT

kk@X201:~$ sudo dislocker -r -V /dev/sdb1 -p628991-613107-434808-569602-000000-000000-000000-000000 -- /media/windows

kk@X201:~$ su
Password: 
root@X201:/home/kk# cd /media/
cdrom/   cdrom0/  kk/      mount/   windows/ 
root@X201:/home/kk# cd /media/windows/
root@X201:/media/windows# ls
dislocker-file

here i can see the dislocker-file file , 

root@X201:/media/windows# mount -o loop dislocker-file /media/mount
ntfs-3g-mount: mount failed: Permission denied

what does this "Permission" mean ? i use root already .

**Comment by vipzrx** [comment]
root@X201:/home/kk# ls -al /media/windows /media/mount/
/media/mount/:
total 8
drwxr-xr-x 2 root root 4096 Aug 20 03:44 .
drwxr-xr-x 6 root root 4096 Aug 20 03:44 ..

/media/windows:
total 4
dr-xr-xr-x 2 root root             0 Dec 31  1969 .
drwxr-xr-x 6 root root          4096 Aug 20 03:44 ..
-r--r--r-- 1 root root 1000202042880 Dec 31  1969 dislocker-file

**Comment by Aorimn** [comment]
It can mean different things:
- It can be a sudo issue: try using dislocker after you su to root.
- It can be your mount version needing the `-o ro` argument, as you use the `-r` argument of dislocker.

**Comment by Aorimn** [comment]
Any news on this @vipzrx?

**Comment by ochompsky** [comment]
@Aorimn im getting the same error.  read only works fine but i cannot get read/write to work.  

first command:
`sudo dislocker -r -V /dev/sdb1 -upw -- /media/encrypted -o allow_other`

read only command that works:
`sudo mount -o loop,ro /media/encrypted/dislocker-file /media/decrypted`

read/write command that fails:
```
sudo mount -o loop,rw /media/encrypted/dislocker-file /media/decrypted
ntfs-3g-mount: mount failed: Permission denied
```

**Comment by MassimilianoN** [comment]
I'm Italian, I don't speak English very well.

I've the same problem:

root@adriano-N150P-N210P-N220P:/media# dislocker-fuse -r -V /dev/sdc2 -p219010-xxxxxxxxxxxxxxxxxxxxxxxxxxx -- /media/bitlocker

root@adriano-N150P-N210P-N220P:/media# mount -o loop /media/bitlocker/dislocker-file /media/mount

ntfs-3g-mount: mount failed: Permesso negato

I've tried with sudo comand too, but I get the same results
root@adriano-N150P-N210P-N220P:/media# mount -o r,loop /media/bitlocker/dislocker-file /media/mount

ntfs-3g-mount: mount failed: Permesso negato

Any tips?

**Comment by Aorimn** [comment]
Hi, the option to mount a partition as read-only for mount.ntfs is ro, not r, thus try this command instead after running dislocker:
`mount -o ro,loop /media/bitlocker/dislocker-file /media/mount`

**Comment by MassimilianoN** [comment]
You are right.
Problem solved, thank you :)

P.s.: First I restarted the system. Probably that's not important...

**Comment by Aorimn** [comment]
It shouldn't be important indeed. I'm glad it works for you!

**Comment by arkh91** [comment]
> Hi, the option to mount a partition as read-only for mount.ntfs is ro, not r, thus try this command instead after running dislocker:
> `mount -o ro,loop /media/bitlocker/dislocker-file /media/mount`

Had the same issue and worked for me. Thx

**Comment by gitcnd** [comment]
In my case, this solved the problem:
`ntfs-3g -o ro,recover dislocker-file /media/mount 
`
Turns out that ntfs-3g spits the "permission denied" error when other stuff was the cause... like hibernated windows volumes etc.
