### ISSUE TITLE
fuse.h not found

### ISSUE THREAD

**Issue by g33kyaditya** [Aorimn/dislocker#87]
CMake dependencies are resolved. After it, running 
`make` 
shows the error 
`/src/dislocker-fuse.c:39:19: fatal error: fuse.h: No such file or directory
 # include <fuse.h>`

**Comment by Aorimn** [comment]
You might need to install fuse headers.

**Comment by g33kyaditya** [comment]
Yes. But that didn't show up while running cmake (as a dependency). Perhaps a find_package() should be added

**Comment by Aorimn** [comment]
That's a good idea, I'll look into it.

**Comment by Aorimn** [comment]
Hi,
This should be fixed now, as a new version is out.
