### ISSUE TITLE
Error building dislocker with clang

### ISSUE THREAD

**Issue by slacka** [Aorimn/dislocker#92]
Trying to build dislocker with clang results in:
`
ruby.h:933:1: error: attribute 'deprecated' is ignored, place it after "struct" to apply attribute to type declaration`

The full log of this error can be found here:
http://clang.debian.net/logs/2016-08-30/dislocker_0.6.1-6_unstable_clang.log

**Comment by Aorimn** [comment]
Thanks for the report, this should be fixed on the develop branch (by removing the -Werror flag).

**Comment by Aorimn** [comment]
Hi,
This should be fixed now, as a new version is out.
