### ISSUE TITLE
Usage / documentation question

### ISSUE THREAD

**Issue by esteinholtz** [Aorimn/dislocker#93]
Hello, thanks for a great piece of software.

This might be more of  a wiki question as it is regarding usage, some clarifications etc. But the wiki didn't seem to be in use. I need some clarifications regarding the parameters as well as input on strategy in a desperate situation (well crashed disks tend to be desperate situations, and only more so when BitLocked... :-)

0) background: Disk is crashed badly, bc partition tables are lost. Not a good situation for a bitLocked disk. I have a 256GB internal SDD that was running windows 10. I believe (TBC) it had 3 partitions with the c: starting after 812 MB. I have the recovery key.

1) Question on basic bitlocker architecture; More precisely: in my situation where GPT  is lost, will there be any unencrypted portions of data such as partition headers, file system headers that will help disk analysers (parted or testdisk for instance) to find the lost structure as a first step?
If that is possible, then I am out of luck, bc I have tried and parted and testdisk both fail in finding the partitions.
If, on the other hand, the entire disk can be encrypted (like the frequently used term "full disk encryption" suggests) then I wouldn't expect any help from parted or testdisk. I would rather use a brute-force approach and try the offset parameter of dislocker around areas where I have reason to believe that the partition borders were. Which leads me to the second question, a documentation enhancement request:

2) what is the metric of the offset parameter? Bytes? Sectors? If sectors, then does it automagically align with the actual sector size of the disk? (This is a doc enhancement request :-D) 

3) Another (bold, I suppose) enhancement request: Is there any way to force dislocker past checking the file system headers and just decrypt whatever it finds at a certain offset? Yes it sounds crazy and is further challenged by the fact that the BitLocker encryption includes relative sector addresses (if i remember correctly). But as a last resort and support for a brute-force approach. Potentially some header info would have to be input as parameters instead.

4) oops, forgot the obvious question: Is win 10 disks supported? I get differernt information in different places.

please advise if you think there is a better way to go about this. Yes I am about to give up, but just a little too stubborn yet.

**Comment by Aorimn** [comment]
I'll try to answer to all your questions, and update the documentation accordingly:

0) That's a shame! I wish you good luck in the data recovery.

1) There're multiple ways to find a BitLocker-ed partition among a full volume:
- The first one would be to look for the volume's signature: 8 bytes, "-FVE-FS-" for BitLocker-ed partitions, at the offset 3, in bytes, of the partition. Note that this signature can be found elsewhere, especially in a clear partition, and in metadata headers (continue reading for this last one).
- In the same spirit, you can look for the INFORMATION_GUID, which are [16 bytes](https://github.com/Aorimn/dislocker/blob/master/src/metadata/guid.c#L32). This GUID is at the offset 0xa0, in bytes, from the begining of the partition.
- Returning to the "-FVE-FS-" signature: it's also the signature which is used to identify BitLocker's metadata (the so-called [information structure](https://github.com/Aorimn/dislocker/blob/master/include/dislocker/metadata/metadata.priv.h#L156)). In this case, it's followed by 2 bytes, then 0x0002 (beware of endianness). Now : there are 3 of these structures dispatched in the encrypted partition, but each of these structures stores all of the [relative address](https://github.com/Aorimn/dislocker/blob/master/include/dislocker/metadata/metadata.priv.h#L175) of the 3 structures. So, once you identify one of these structures, you just have 3 possible addresses for the beginning of your partition.

All of this is, of course, on a sane encrypted partition. In your case, you might have to struggle with the addresses and all.

2) The metric is in bytes, the documentation is updated on the develop branch.

3) This is a feature request I have to think about, but it won't be implemented in a near future: there're a lot of checks before enabling the volume's decrytion. The main problem I see is people thinking it's a good idea not to check anything and destroying their data. The key decryption process includes a MAC, which should prevent any major damage, but you might also want to disable MAC checking, of course.

4) Support for Windows 10 encrypted partition is [supported](https://github.com/Aorimn/dislocker/blob/master/CHANGELOG.md) in dislocker

I'm not sure there's any good way in your case. For searching strings, you can use `strings --radix=d |grep -FVE-FS-` (not sure it's the best solution, just a quick one to find).

Any way, good luck with this, I wouldn't want to be in your place. Thank you for your comments.

**Comment by esteinholtz** [comment]
Thanks for an elaborate answer! I was struggling to understand the INFORMATION_GUID piece, not understanding you talked about and actual constant in your actual code, but thanks to the link I got it. I am doing a search for the -FVE-FS- signature now just like you suggested, couldnt think of a better way except for writing a script. The INFORMATION_GUID I'll do next but have to confirm endianness first. I am on x86_64 so that would be little endian I think. Does that mean that your hex values in INFORMATION_GUID go unconverted? 
right now struggling a  bit with getting the shell commands to work for this, maybe python is better... I'll be back soon :-).

I totally understand your response to the "in the wild" option to skip header checks. I thought of it as an equivalent to what happens when you whimsically try to eg fsck -f on a mounted volume. (yes I've done that :-) )  A warning to the meaning of "do you know that what you are attempting is stupid in most cases and can cause severe damage ..." etc. But I'll leave it at that. Developers who puts integrity and stability high should be respected and well-paid :-). If the day comes I may save an image of my sour disk in expectation ... :-). 

I guess the only option left if I dont succeed in finding the headers by random search is the brute-force approach, although with fake headers inserted instead. But that is probably beyond the effort I can spend to save my little baby ...  :-). If seriously approached though, could be a bitlocker-specific disk-rescue tool useful for others as well.

**Comment by esteinholtz** [comment]
and let me just add a more distinct version of question 1 (not sure I got this from your answer above): 
is bitlocker encrypting the file system only rather than the full disk including partition signatures etc? From your answer above this seems to be the case, just confirming.

**Comment by esteinholtz** [comment]
...wait... just realised question 1 is answered: since you always apply dislocker to eg /dev/sda1, encryption must be on file system only level, or partitions wouldnt be visible...

**Comment by esteinholtz** [comment]
Thanks for your help and for taking free time. Indeed this looked too professional to me to be a sparetime project, but you never know!

...and no -FVE-FS- signature were found, plus searching for INFORMATION_GUID gave me a nightmare. All I can say to anyone wanting to read binary data in python is dont go there :-/. I am really puzzled by how thoroughly the disk has been wiped though I didnt do any actual mistake. I can only think of an attack as the explanation.

Thanks for the tip about DFF. I thought I had dug up about every open-source disk rescueish tool there is out there, but this looks very promising from the website at least. I'll definitely give it a try as my last strand of hope... 

Thanks again, and keep up the good work, Cross-platform portability is super-important. (Humor: I thought you were paid by someone who wanted to combat the M$ lock-in strategy :-) )

**Comment by rossica** [comment]
You might also try looking at the open-source TestDisk utility 
http://www.cgsecurity.org/wiki/TestDisk to at least recover the 
partition structure. From there you might be able to recover the 
bitlocker filesystems.

I've used this for recovering deleted partitions in the past. (note: 
don't do partition-level edits at 3am without caffeine and you wont need 
this tool)
