### ISSUE TITLE
Failed to read in #3: Input/output error

### ISSUE THREAD

**Issue by mys007** [Aorimn/dislocker#97]
I run into a problem with mounting a bitlocked partition with hardware encryption from Windows 10 Pro (Version 1607, Build 14393) on Ubuntu 16. This is the detailed log:
```
ubuntu@ubuntu:~$ sudo dislocker -vvvv -r -V /dev/sda4
Fri Dec 16 11:19:37 2016 [DEBUG] Verbosity level to DEBUG (4) into 'stdout'
Fri Dec 16 11:19:37 2016 [INFO] dislocker by Romain Coltel, v0.6.1 (compiled for Linux/x86_64)
Fri Dec 16 11:19:37 2016 [INFO] Compiled version: master:bcc8ed8
Fri Dec 16 11:19:37 2016 [DEBUG] --- Config...
Fri Dec 16 11:19:37 2016 [DEBUG]    Verbosity: 4
Fri Dec 16 11:19:37 2016 [DEBUG]    Trying to decrypt '/dev/sda4'
Fri Dec 16 11:19:37 2016 [DEBUG]        using a clear key on the volume
Fri Dec 16 11:19:37 2016 [DEBUG]    Using the first valid metadata block
Fri Dec 16 11:19:37 2016 [DEBUG]    Not allowing any write on the BitLocker volume (read only mode)
Fri Dec 16 11:19:37 2016 [DEBUG] ... End config ---
Fri Dec 16 11:19:37 2016 [DEBUG] Trying to open '/dev/sda4'...
Fri Dec 16 11:19:37 2016 [DEBUG] Trying to open '/dev/sda4'...
Fri Dec 16 11:19:37 2016 [DEBUG] Opened (fd #3).
Fri Dec 16 11:19:37 2016 [DEBUG] Opened (fd #3).
Fri Dec 16 11:19:37 2016 [DEBUG] New memory allocation at 0x56344d1a3580 (0x18 bytes allocated)
Fri Dec 16 11:19:37 2016 [DEBUG] New memory allocation at 0x56344d1a35a0 (0x90 bytes allocated)
Fri Dec 16 11:19:37 2016 [DEBUG] New memory allocation at 0x56344d1a3640 (0x200 bytes allocated)
Fri Dec 16 11:19:37 2016 [DEBUG] Positionnong #3 at offset 0 from 0
Fri Dec 16 11:19:37 2016 [DEBUG] Reading volume header...
Fri Dec 16 11:19:37 2016 [DEBUG] Reading 0x200 bytes from #3 into 0x56344d1a3640
Fri Dec 16 11:19:37 2016 [ERROR] Failed to read in #3: Input/output error
Fri Dec 16 11:19:37 2016 [CRITICAL] Error during reading the volume: not enough byte read.
Fri Dec 16 11:19:37 2016 [DEBUG] Freeing pointer at address 0x56344d1a3640
Fri Dec 16 11:19:37 2016 [DEBUG] Freeing pointer at address 0x56344d1a3580
Fri Dec 16 11:19:37 2016 [DEBUG] Freeing pointer at address 0x56344d1a35a0
Fri Dec 16 11:19:37 2016 [DEBUG] Freeing pointer at address 0x56344d1a20f0
Fri Dec 16 11:19:37 2016 [DEBUG] Trying to close fd #3...
```
with my partitioning being
```
Disklabel type: gpt
Disk identifier: 8A7A1B2A-2DF1-4298-996B-BDA68570E5E1
 
Device         Start        End    Sectors   Size Type
/dev/sda1       2048     923647     921600   450M Windows recovery environment
/dev/sda2     923648    1126399     202752    99M EFI System
/dev/sda3    1126400    1159167      32768    16M Microsoft reserved
/dev/sda4    1159168  409599999  408440832 194.8G Microsoft basic data
/dev/sda5  409600000 1465147391 1055547392 503.3G Microsoft basic data
```
At this early stage, I don't think it matters if I'm choosing the right decryption method (-c,-p,-u). Thanks for any hint and for your great opensource work!

**Comment by Aorimn** [comment]
Indeed, it doesn't matter yet for the decryption method, it gets stopped at the first read on the volume. I have a few questions in order for me to help you:
1) Can you run the following command and give me the result, using the same user you're using when trying to run dislocker: `sudo dd if=/dev/sda4 of=/tmp/dd bs=512 count=1`?
2) How did you installed dislocker?
3) Which Ubuntu 16 version are you using, 16.04 or 16.11?

**Comment by mys007** [comment]
Thanks for your reply.

1. Surprisingly, I get an error (dmesg log at http://pastebin.com/ELgz5br8):
```
ubuntu@ubuntu:~$ sudo dd if=/dev/sda4 of=/tmp/dd bs=512 count=1
dd: error reading '/dev/sda4': Input/output error
0+0 records in
0+0 records out
0 bytes copied, 0.0959254 s, 0.0 kB/s
```
I do get the same error with sda5 (another encrypted partition) but not with sda1..sda3 (the standard set of small compulsory partitions), those get read fine.

2. From the latest sources at github. Any required libraries were acquired with `apt`.

3. 16.04.1

**Comment by Aorimn** [comment]
`dd` not being able to read `/dev/sda4` shows taht dislocker isn't the problem here.

However, what could be, I don't know. Can you try accessing the same sector, but through `/dev/sda`, like so:
`sudo dd if=/dev/sda of=/tmp/dd skip=1159168 bs=512 count=1`

I wouldn't go too far in the following assumption, but I think the problem is caused by the Linux kernel here.

**Comment by mys007** [comment]
Sorry for the delay. Indeed, `dd` is not able to read the disk with the `skip` parameter either. So the problem is something in bios (dell e7440) or ssd (crucial mx300). Thanks for your help!
