### ISSUE TITLE
Shared Library how to's

### ISSUE THREAD

**Issue by kakashi02** [Aorimn/dislocker#98]
locker.dir/ruby.c.o
[ 78%] Linking C shared library libdislocker.so
/usr/bin/ld: /usr/local/lib/libmbedcrypto.a(aes.c.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libmbedcrypto.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/CMakeFiles/dislocker.dir/build.make:822: recipe for target 'src/libdislocker.so.0.6.1' failed
make[2]: *** [src/libdislocker.so.0.6.1] Error 1
CMakeFiles/Makefile2:239: recipe for target 'src/CMakeFiles/dislocker.dir/all' failed
make[1]: *** [src/CMakeFiles/dislocker.dir/all]

Hi,

I would like to seek your assistance on enabling the shared library as it gives me an error. Not very familir in Ubuntu well. I need the dislocker to backup files as it was been bitlocked accidentally. Thank you

**Comment by kakashi02** [comment]
also this one:


oot@ubuntu:~/Desktop/dislocker# make clean
root@ubuntu:~/Desktop/dislocker# make
[  2%] Building C object src/CMakeFiles/dislocker.dir/dislocker.c.o
[  5%] Building C object src/CMakeFiles/dislocker.dir/common.c.o
[  7%] Building C object src/CMakeFiles/dislocker.dir/config.c.o
[ 10%] Building C object src/CMakeFiles/dislocker.dir/xstd/xstdio.c.o
[ 13%] Building C object src/CMakeFiles/dislocker.dir/xstd/xstdlib.c.o
[ 15%] Building C object src/CMakeFiles/dislocker.dir/metadata/datums.c.o
[ 18%] Building C object src/CMakeFiles/dislocker.dir/metadata/metadata.c.o
[ 21%] Building C object src/CMakeFiles/dislocker.dir/metadata/vmk.c.o
[ 23%] Building C object src/CMakeFiles/dislocker.dir/metadata/fvek.c.o
[ 26%] Building C object src/CMakeFiles/dislocker.dir/metadata/extended_info.c.o
[ 28%] Building C object src/CMakeFiles/dislocker.dir/metadata/guid.c.o
[ 31%] Building C object src/CMakeFiles/dislocker.dir/metadata/print_metadata.c.o
[ 34%] Building C object src/CMakeFiles/dislocker.dir/accesses/stretch_key.c.o
[ 36%] Building C object src/CMakeFiles/dislocker.dir/accesses/accesses.c.o
[ 39%] Building C object src/CMakeFiles/dislocker.dir/accesses/rp/recovery_password.c.o
[ 42%] Building C object src/CMakeFiles/dislocker.dir/accesses/user_pass/user_pass.c.o
[ 44%] Building C object src/CMakeFiles/dislocker.dir/accesses/bek/bekfile.c.o
[ 47%] Building C object src/CMakeFiles/dislocker.dir/encryption/encommon.c.o
[ 50%] Building C object src/CMakeFiles/dislocker.dir/encryption/decrypt.c.o
[ 52%] Building C object src/CMakeFiles/dislocker.dir/encryption/encrypt.c.o
[ 55%] Building C object src/CMakeFiles/dislocker.dir/encryption/diffuser.c.o
[ 57%] Building C object src/CMakeFiles/dislocker.dir/encryption/crc32.c.o
[ 60%] Building C object src/CMakeFiles/dislocker.dir/encryption/aes-xts.c.o
[ 63%] Building C object src/CMakeFiles/dislocker.dir/ntfs/clock.c.o
[ 65%] Building C object src/CMakeFiles/dislocker.dir/ntfs/encoding.c.o
[ 68%] Building C object src/CMakeFiles/dislocker.dir/inouts/inouts.c.o
[ 71%] Building C object src/CMakeFiles/dislocker.dir/inouts/prepare.c.o
[ 73%] Building C object src/CMakeFiles/dislocker.dir/inouts/sectors.c.o
[ 76%] Building C object src/CMakeFiles/dislocker.dir/ruby.c.o
[ 78%] Linking C shared library libdislocker.so
[ 78%] Built target dislocker
[ 81%] Building C object src/CMakeFiles/dislocker-metadata.dir/dislocker-metadata.c.o
[ 84%] Linking C executable dislocker-metadata
libdislocker.so.0.6.1: undefined reference to `mbedtls_sha256'
libdislocker.so.0.6.1: undefined reference to `mbedtls_aes_setkey_dec'
libdislocker.so.0.6.1: undefined reference to `mbedtls_aes_crypt_ecb'
libdislocker.so.0.6.1: undefined reference to `mbedtls_aes_setkey_enc'
libdislocker.so.0.6.1: undefined reference to `mbedtls_aes_crypt_cbc'
collect2: error: ld returned 1 exit status
src/CMakeFiles/dislocker-metadata.dir/build.make:95: recipe for target 'src/dislocker-metadata' failed
make[2]: *** [src/dislocker-metadata] Error 1
CMakeFiles/Makefile2:128: recipe for target 'src/CMakeFiles/dislocker-metadata.dir/all' failed
make[1]: *** [src/CMakeFiles/dislocker-metadata.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Aorimn** [comment]
Hi,
Did you close this issue because you found how to compile dislocker with mbedtls (which involve in fact recompiling mbedtls with the `-fPIC` flag)?

**Comment by kakashi02** [comment]
nope.. m

**Comment by kakashi02** [comment]
sorry must have mistakenly closed the issue. that is what I find it confusing.. actually I downloaded 2 kinds of dislocker. one is on your site, and the other is on ubuntu wherein the 1st one is from your site and the 2nd one is from ubuntu, hope you can help me on this. Thank you

**Comment by kakashi02** [comment]
still there?

**Comment by kakashi02** [comment]
please help

**Comment by kakashi02** [comment]
unresolved... unresponsive

**Comment by Aorimn** [comment]
I was working today and couldn't answer here.

For making the first working, recompile mbedtls and install this compiled version, then recompile dislocker.

**Comment by kakashi02** [comment]
Here's the scenario, I am using Ubuntu 16.04 wherein I have installed it on an USB to decrypt the HDD laptop.

Questions:

1. would it be possible to install dislocker even I am using an Ubuntu on USB
2. Do you have any install directions that is more precise/exact? As I have noticed that there is a shortcut on the Installation.md and it is lacking a process. Like... ooooops.. what would I do? I have encountered an error.
3. Will I install this using a root access or not?
4. How can I use recompile mbedtls? Can you provide a step-by-step process?
5. where will I install it? Downloads, Desktop, etc..?

Hope you can reply to this concern the soonest, Thanks

**Comment by Aorimn** [comment]
1. Doesn't matter.
2. No I don't.
3. However you want, it will only change how you use it.
4. Check out the mbedtls [website.](https://github.com/ARMmbed/mbedtls)
5. If it is mbedtls, you should install it on your system in order not to bother with compile options and LD_LIBRARY_PATH.
